In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
pd.options.display.max_colwidth = 200

In [3]:
cmr=  pd.read_excel('Mayo 02_2023/Reporte_Cmr.xlsx', parse_dates= ['FECHA DE REGISTRO','HORA DE REGISTRO','FECHA DE ULTIMA INTERACION'])

In [4]:
cmr.columns

Index(['FECHA DE REGISTRO', 'HORA DE REGISTRO', 'VENDEDORES', 'ORIGEN',
       'DIRECCION', 'QUE BUSCA', 'TIPO LOTES', 'PRECIOS', 'OBSERVACION',
       'HORARIO DISPONIBLE', 'nom', 'ape', 'CLIENTE', 'DNI', 'TELEFONO',
       'NIVEL DE INTERES', 'NOMBRE PROXIMO EVENTO', 'FECHA PROXIMO EVENTO',
       'FECHA DE ULTIMA INTERACION'],
      dtype='object')

In [5]:
cmr.shape[0]

17732

In [6]:
cmr['CLIENTE'] = cmr['CLIENTE'].str.strip().str.upper()

In [7]:
cmr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17732 entries, 0 to 17731
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA DE REGISTRO           17732 non-null  datetime64[ns]
 1   HORA DE REGISTRO            8092 non-null   datetime64[ns]
 2   VENDEDORES                  17719 non-null  object
 3   ORIGEN                      17732 non-null  object
 4   DIRECCION                   148 non-null    object
 5   QUE BUSCA                   47 non-null     object
 6   TIPO LOTES                  70 non-null     object
 7   PRECIOS                     70 non-null     object
 8   OBSERVACION                 8508 non-null   object
 9   HORARIO DISPONIBLE          501 non-null    object
 10  nom                         17725 non-null  object
 11  ape                         17140 non-null  object
 12  CLIENTE                     17732 non-null  object
 13  DNI                         9137 non-null   object
 14  TELEFONO                    17725 non-null  object
 15  NIVEL DE INTERES            15981 non-null  object
 16  NOMBRE PROXIMO EVENTO       5531 non-null   object
 17  FECHA PROXIMO EVENTO        5531 non-null   object
 18  FECHA DE ULTIMA INTERACION  17718 non-null  datetime64[ns]
dtypes: datetime64[ns](3), object(16)
memory usage: 2.6+ MB

In [7]:
leads=  pd.read_excel('Mayo 02_2023/Reporte_Leads_Contactados.xlsx',header=2, parse_dates=['FECHA REGISTRO'])

In [8]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DNI             1681 non-null   float64
 1   APELLIDOS       1681 non-null   object
 2   NOMBRE          1681 non-null   object
 3   CANAL           1681 non-null   object
 4   CORREO          230 non-null    object
 5   CELULAR         1681 non-null   float64
 6   CELULAR2        22 non-null     float64
 7   DIRECCION       1675 non-null   object
 8   EST.CIVIL       1681 non-null   object
 9   CO-PROPI        1688 non-null   object
 10  DNI EMISION     2 non-null      object
 11  DNI VENCE       0 non-null      float64
 12  VENDEDOR        1678 non-null   object
 13  FECHA REGISTRO  1688 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(9)
memory usage: 184.8+ KB

In [9]:
leads = leads.drop(range(0, 7, 1),axis=0)

In [10]:
leads = leads.iloc[:,[13,0,1,2,3,5,12,7]]

In [11]:
leads['NOMBRE'] = leads['NOMBRE'].str.strip().str.upper()
leads['APELLIDOS'] = leads['APELLIDOS'].str.strip().str.upper()
leads['VENDEDOR'] = leads['VENDEDOR'].str.strip().str.upper()
leads['VENDEDOR'] = leads['VENDEDOR'].fillna('OFICINA')
leads['CLIENTE'] = leads['NOMBRE']+ ' '+leads['APELLIDOS']
leads['CLIENTE'] = leads['CLIENTE'].str.strip().str.upper()
leads['DNI'] = leads['DNI'].astype(int).astype(str)
leads = leads[~(leads['CLIENTE']=='EDITAR_NOMBRE_CALLCENTER EDITAR_NOMBRE_CALLCENTER')]

In [12]:
leads.drop(['APELLIDOS','NOMBRE'],axis=1, inplace= True)

In [13]:
leads

,FECHA REGISTRO,DNI,CANAL,CELULAR,VENDEDOR,DIRECCION,CLIENTE
7,2022-04-22,42800980,Facebook,9.961397e+08,RUBEN MADRID SIANCAS,LIMA,KRISTOPHER MARIO BOMBILLA CAUTIN
8,2022-04-26,75830260,Facebook,9.421943e+08,KENNY SMITH SANCARRANCO BAZAN,LIMA,RODRIGO CARRASCO PRO
9,2021-11-05,46858479,Referido de cliente,9.306162e+08,LUZ MARINA DOMENACK HERRERA,PIURA,KEYLA ELIZABETH CRUZ VERA
10,2022-11-09,74306414,Facebook,9.172944e+08,RUBEN MADRID SIANCAS,PAITA,MERCY IDROGO
11,2021-07-02,46205800,Convenio Colegio de Obstetras,1.000000e+09,ROSSY MARY YAMPUFE YARLEQUE,TAMBOGRANDE,PAOLA JUAREZ
...,...,...,...,...,...,...,...
1683,2022-06-21,10051062,Referido de colaborador,5.699420e+10,RUBEN MADRID SIANCAS,LA SERENA - CHILE,SERGIO FERNANDO ZUÑIGA JARA
1684,2022-04-09,25758062,Panel Publicitario,9.752321e+08,KENNY SMITH SANCARRANCO BAZAN,PIURA,DANTE IVAN ZUÑIGA LA ROSA
1685,2022-07-04,2874086,Referido de colaborador,9.515461e+08,WILMER NOE CAMPOVERDE JIMENEZ,AV. LUIS MONTERO MZ. O LT 1-35 - URB. MIRAFLORES - CASTILLA - PIURA,MARIA PAOLA ZUÑIGA ROJAS
1686,2021-11-13,3370522,Referido de colaborador,9.690169e+08,FRANCISCO JAVIER ZAPATA LEON,CASTILLA,SILVIA PILAR ZUÑIGA SARANGO
1687,2021-06-26,3829470,Convenio Colegio Medico,9.695106e+08,MILAGROS DEL PILAR TRELLES DEZA,URB. BANCO DE LA NACION 6 BARRIO PARTICULAR,RICARDO CESAR ZUÑIGA VALLEJOS

In [14]:
leads_migra = pd.read_excel('Mayo 02_2023/Reporte_Migrados.xlsx',header=2, parse_dates=['FECHA MIGRA'])

In [15]:
leads_migra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FECHA MIGRA  1125 non-null   datetime64[ns]
 1   DNI          1122 non-null   object
 2   APELLIDOS    1122 non-null   object
 3   NOMBRE       1122 non-null   object
 4   CANAL        1114 non-null   object
 5   CORREO       808 non-null    object
 6   CELULAR      1122 non-null   object
 7   CELULAR2     116 non-null    float64
 8   DIRECCION    1122 non-null   object
 9   EST.CIVIL    1122 non-null   object
 10  CO-PROPI     1122 non-null   object
 11  DNI EMISION  689 non-null    object
 12  DNI VENCE    0 non-null      float64
 13  VENDEDOR     1122 non-null   object
dtypes: datetime64[ns](1), float64(2), object(11)
memory usage: 123.2+ KB

In [16]:
leads_migra = leads_migra[~(leads_migra['DNI'].isnull())]

In [17]:
leads_migra = leads_migra.iloc[:,[0,13,1,2,3,4,6,8]]

In [18]:
leads_migra['NOMBRE'] = leads_migra['NOMBRE'].str.strip().str.upper()
leads_migra['APELLIDOS'] = leads_migra['APELLIDOS'].str.strip().str.upper()
leads_migra['VENDEDOR'] = leads_migra['VENDEDOR'].str.strip().str.upper()
leads_migra['CLIENTE'] = leads_migra['NOMBRE']+ ' '+leads_migra['APELLIDOS']

In [19]:
leads_migra['DNI'] = leads_migra['DNI'].astype(str)
leads_migra['DNI'] = leads_migra['DNI'].str.replace('auto-33918','33918')

In [20]:
leads_migra.drop(['APELLIDOS','NOMBRE'],axis=1, inplace= True)
leads_migra.rename(columns={'FECHA MIGRA':'FECHA REGISTRO'}, inplace= True)

In [21]:
leads_migra

,FECHA REGISTRO,VENDEDOR,DNI,CANAL,CELULAR,DIRECCION,CLIENTE
0,2023-04-29,OMAR CAPUÑAY ROSALES,42309969,Lading Page,946548975,JR. BOLOGNESI 741,GASPAR SEVILLANO BARRETO
1,2023-04-26,LUIS FERNANDO DELGADO WONG,26644425,NaN,976961570,JR. LAS CASUARINAS 797,JOSE JORGE RONCAL NARVAEZ
2,2023-04-25,RAMIRO CIRO ERNESTO AVILES RUIZ,44328064,NaN,953677750,AV. BUGAMBILLAS 426,LUIS ALBERTO LEA TICONA
3,2023-04-25,RAMIRO CIRO ERNESTO AVILES RUIZ,417925,Facebook,953677750,AV. BUGAMBILLAS 426,MARISOL LEA
4,2023-04-24,BRIAN ANDRE MONDRAGON FLORES,18161689,Facebook,990809904,URB SAN ISIDRO 2DA ETAPA MZ T1 LOTE 8,CARLOS ANTONIO GONZALEZ RIOS
...,...,...,...,...,...,...,...
1120,2021-02-18,KENNY SMITH SANCARRANCO BAZAN,9920379,Facebook,970280027,AV. IRAZOLA MZ. C LT. 34 URB. MIRAFLORES,CIELO JANE HUAMAN ASTUDILLO
1121,2021-02-18,ANDRES BARRAGAN IGLESIAS,42724931,Facebook,990569303,PIURA,DIEGO ALFONSO YEPES MANRIQUEZ
1122,2021-02-18,MILAGROS DEL PILAR TRELLES DEZA,2667241,Facebook,969640952,MZ. N1-23 URB. MIRAFLORES ETAPA II,HAROLD OSWALDO CAVERO PORTILLA
1123,2021-02-18,OSCAR ANDRES MIRANDA VEGA,42386242,Facebook,987490141,CONDOMINIO CLUB PARQUES DEL CHIPE MZ. L LOTE 02,RODOLFO ALFREDO TAVARA RODRICH
1124,2021-02-18,MILAGROS DEL PILAR TRELLES DEZA,43953978,Facebook,995279881,MZ. N1-23 URB. MIRAFLORES ETAPA II,HAROLD ANDRES CAVERO PAREDES

In [22]:
leads_unidos = pd.concat([leads,leads_migra])

In [23]:
leads_unidos['CLIENTE'] = leads_unidos['CLIENTE'].str.replace('    ',' ')
leads_unidos['CLIENTE'] = leads_unidos['CLIENTE'].str.replace('   ',' ')
leads_unidos['CLIENTE'] = leads_unidos['CLIENTE'].str.replace('  ',' ')
#leads_unidos[leads_unidos['CLIENTE'].str.contains('')]

### GLOBAL DE VENTAS

In [25]:
ventas = pd.read_excel('Mayo 02_2023/Reporte_todas_las_ventas_copy.xlsx',header=2, parse_dates=['FECHA VENTA','HORA VENTA'])

In [26]:
#ventas2 = pd.read_excel('Reporte_todas_las_ventas.xlsx',header=2, parse_dates=['FECHA VENTA','HORA VENTA'])

In [27]:
#ventas2[ventas2['CODIGO']=='VN0001315']

In [28]:
# SON DE SETIEMBRE POR ESONO LAS CONSIDERO PERO DEBERIA CAMBIRLE LA FECHA SON DE FIN DE MES

In [29]:
# 'VN0001315'  -- DH01 OCTUBRE   
# 'VN0001273'  -- DN10 OCTUBRE -Pagando cuota

In [30]:
#ventas = ventas[~((ventas['CODIGO']=='VN0001315')|\
                  #(ventas['CODIGO']=='VN0001273')|\
                  #(ventas['CODIGO']=='VN0001271'))]  # DH01 OCTUBRE \ DD04 OCTUBRE  \DN10 OCTUBRE

In [31]:
ventas.rename(columns={'NOMBRE COMPLETO':'CLIENTE'},inplace= True)

In [32]:
ventas_totales = ventas[~(ventas['ESTADO VENTA']=='ANULADA')]

In [33]:
ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.upper().str.strip()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\3606012212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.upper().str.strip()

In [34]:
ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('    ',' ')
ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('   ',' ')
ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('  ',' ')
#ventas_totales_pagando[ventas_totales_pagando['CLIENTE'].str.contains('     ')]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\2565124947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('    ',' ')
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\2565124947.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('   ',' ')
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\2565124947.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas_totales['CLIENTE'] = ventas_totales['CLIENTE'].str.replace('  ',' ')

In [35]:
cliente_excel_ventas = ventas_totales['CLIENTE'].unique().tolist()
len(cliente_excel_ventas)

926

In [36]:
ventas_totales.shape[0]

1122

In [37]:
ventas_totales['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    762
VENCIDA           149
RESOLUCIÓN         77
DEVOLUCION C.I     48
DESISTIMIENTO      47
PRE-RESUELTO       32
SEPARACION          7
Name: ESTADO VENTA, dtype: int64

In [38]:
ventas_totales

,FECHA VENTA,HORA VENTA,DNI,CLIENTE,VENDEDOR,CODIGO,LOTE,ubicacion,PRECIO,PrecioCliente,N CUOTAS,ESTADO VENTA,FechaDeposito,contrato,fecha_contrato,formapago
0,2023-04-29,2023-05-02 11:29:18,42309969,GASPAR SEVILLANO BARRETO,OMAR CAPUÑAY ROSALES,VN0001556,AG06,ESQUINA - FRENTE A ALAMEDA,253854.81,253854.81,158,SEPARACION,2023-04-27,NaN,NaN,FINANCIADO
1,2023-04-26,2023-05-02 17:55:17,26644425,JOSE JORGE RONCAL NARVAEZ,LUIS FERNANDO DELGADO WONG,VN0001555,BJ26,FRENTE A PARQUE,60275.24,60275.24,168,PAGANDO CUOTAS,2023-04-26,1338.0,2023-04-26,FINANCIADO
2,2023-04-25,2023-05-02 11:40:07,44328064,LUIS ALBERTO LEA TICONA,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001554,DK15,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO
3,2023-04-25,2023-05-02 11:36:08,417925,MARISOL LEA,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001553,DK14,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO
4,2023-04-24,2023-05-02 12:31:33,18161689,CARLOS ANTONIO GONZALEZ RIOS,BRIAN ANDRE MONDRAGON FLORES,VN0001552,DL16,ESQUINA,56421.18,56421.18,158,PAGANDO CUOTAS,2023-04-28,1340.0,2023-04-28,FINANCIADO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,2021-02-19,2023-05-02 09:33:50,2667241,HAROLD OSWALDO CAVERO PORTILLA,MILAGROS DEL PILAR TRELLES DEZA,VN0000010,EI28,ESQUINA,34387.50,34387.50,120,PAGANDO CUOTAS,2021-02-19,13.0,2021-02-19,FINANCIADO
1538,2021-02-19,2023-05-02 09:33:32,2667241,HAROLD OSWALDO CAVERO PORTILLA,MILAGROS DEL PILAR TRELLES DEZA,VN0000009,EI27,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,12.0,2021-02-19,FINANCIADO
1539,2021-02-19,2023-05-02 09:32:08,2667241,HAROLD OSWALDO CAVERO PORTILLA,MILAGROS DEL PILAR TRELLES DEZA,VN0000008,EI24,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,11.0,2021-02-19,FINANCIADO
1540,2021-02-19,2023-05-02 09:31:58,2667241,HAROLD OSWALDO CAVERO PORTILLA,MILAGROS DEL PILAR TRELLES DEZA,VN0000007,EI23,JARDIN,30471.00,30471.00,120,PAGANDO CUOTAS,2021-02-19,10.0,2021-02-19,FINANCIADO
1543,2021-02-18,2023-05-02 16:40:09,9920379,CIELO JANE HUAMAN ASTUDILLO,KENNY SMITH SANCARRANCO BAZAN,VN0000004,EE25,JARDIN,27394.50,27394.50,120,PAGANDO CUOTAS,2021-02-18,1.0,2021-02-18,FINANCIADO

In [39]:
ventas_totales['FECHA VENTA'].max()

Timestamp('2023-04-29 00:00:00')

### CMR TOTAL

In [40]:
#cmr[cmr['CLIENTE']=='EMMA ROSA DE LOS MILAGROS PIEDRA MAZA']
cmr['CLIENTE'] = cmr['CLIENTE'].str.replace('EMMA ROSA DE LOS MILAGROS PIEDRA MAZA','ENMA ROSA DE LOS MILAGROS PIEDRA MAZA')

In [41]:
#cmr['CLIENTE'] = cmr['CLIENTE'].str.strip().str.upper()
cmr['CLIENTE'] = cmr['CLIENTE'].str.replace('    ',' ')
cmr['CLIENTE'] = cmr['CLIENTE'].str.replace('   ',' ')
cmr['CLIENTE'] = cmr['CLIENTE'].str.replace('  ',' ')
#cmr[cmr['CLIENTE'].str.contains('        ')]
cmr.shape[0]

17732

In [42]:
mini_base_total = cmr[cmr['CLIENTE'].isin(cliente_excel_ventas)]

In [43]:
cliente_duplicados_totales_cmr = mini_base_total[mini_base_total['CLIENTE'].duplicated()]['CLIENTE'].tolist()

In [44]:
mini_base_total[mini_base_total['CLIENTE'].isin(cliente_duplicados_totales_cmr)]

,FECHA DE REGISTRO,HORA DE REGISTRO,VENDEDORES,ORIGEN,DIRECCION,QUE BUSCA,TIPO LOTES,PRECIOS,OBSERVACION,HORARIO DISPONIBLE,nom,ape,CLIENTE,DNI,TELEFONO,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,FECHA DE ULTIMA INTERACION
1803,2023-04-04,2023-05-02 12:09:31,ROCIO,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,ALEJANDRO,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,568181821,+1(786)312-2233,Compro,Llamada,2023-04-13 17:30:00,2023-04-14
2181,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2182,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2183,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2184,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2185,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2186,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2187,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2188,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2189,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2190,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2191,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2192,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2193,2023-04-04,NaT,CALL_CENTER,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alejandro,GUTIERREZ LOZADA,ALEJANDRO GUTIERREZ LOZADA,NaN,+1(786)312-,Por contactar,NaN,NaN,2023-04-04
2283,2023-03-29,2023-05-02 17:15:24,OMAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,JUDITH BETTY,ALVARADO TRUJILLO,JUDITH BETTY ALVARADO TRUJILLO,17804713,940860089,Interesado Alto,NaN,NaN,2023-03-31
2370,2023-03-29,2023-05-02 17:15:28,OMAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,JUDITH BETTY,ALVARADO TRUJILLO,JUDITH BETTY ALVARADO TRUJILLO,17804713,940860089,Compro,NaN,NaN,2023-03-29
4355,2022-11-15,2023-05-02 09:47:51,CINDY MARIELA,Facebook_Leads,NaN,NaN,NaN,NaN,NaN,NaN,MARDY MARIBEL,ALCANTARA OCAS,MARDY MARIBEL ALCANTARA OCAS,75437734,902543282,Compro,NaN,NaN,2023-02-02
4356,2022-11-15,2023-05-02 09:47:51,CINDY MARIELA,Facebook_Leads,NaN,NaN,NaN,NaN,NaN,NaN,MARDY MARIBEL,ALCANTARA OCAS,MARDY MARIBEL ALCANTARA OCAS,75437734,902543282,Compro,NaN,NaN,2023-02-02
8640,2022-10-19,NaT,RAMIRO CIRO ERNESTO,Facebook_Leads,NaN,NaN,NaN,NaN,NaN,NaN,JERSSON DAVID,MORA SARMIENTO,JERSSON DAVID MORA SARMIENTO,001275610,965445227,Compro,NaN,NaN,2022-10-29
9189,2022-10-15,2023-05-02 14:06:17,RAMIRO CIRO ERNESTO,Facebook_Leads,NaN,NaN,NaN,NaN,7 pm,NaN,Jersson David,Mora Sarmiento,JERSSON DAVID MORA SARMIENTO,01275610,965445227,Interesado Alto,Llamada,2022-10-17 16:00:00,2022-10-15
9225,2022-10-12,2023-05-02 22:00:24,MAYRA YESENIA,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,ALAN,RAMOS MIRANDA,ALAN RAMOS MIRANDA,46047833,980898971,Interesado Alto,Llamada,2022-10-15 10:25:00,2022-10-14
9293,2022-10-11,2023-05-02 16:49:42,LUIS FERNANDO,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,JAVIER OSWALDO,TINTAYA CUTIPA,JAVIER OSWALDO TINTAYA CUTIPA,29239469,991850980,Interesado Alto,Llamada,2022-10-25 17:49:00,2022-10-11
9296,2022-10-11,2023-05-02 13:08:05,LUIS FERNANDO,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Javier Oswaldo,TINTAYA CUTIPA,JAVIER OSWALDO TINTAYA CUTIPA,NaN,991850980,Interesado Alto,Cita Virtual,2022-10-11 15:01:00,2022-10-11
9711,2022-09-26,2023-05-02 09:33:26,RUBEN,Pagina_Web,NaN,NaN,NaN,NaN,NaN,NaN,ERICK GIAMPIERE,VARGAS RUIZ,ERICK GIAMPIERE VARGAS RUIZ,46542123,993794005,Compro,Llamada,2022-09-28 10:00:00,2022-09-28
9799,2022-08-06,NaT,KEMBER YASOLI,Pagina_Web,NaN,NaN,NaN,NaN,NaN,10-12pm,ERICK GIAMPIERE VARGAS RUIZ,NaN,ERICK GIAMPIERE VARGAS RUIZ,NaN,993794005,No interesado,Llamada,2022-09-27 16:20:00,2022-09-27
10036,2022-09-19,2023-05-02 13:21:30,MAYRA YESENIA,Call Center,NaN,NaN,NaN,NaN,NaN,NaN,Alan,RAMOS MIRANDA,ALAN RAMOS MIRANDA,NaN,980898971,Interesado Alto,Cita Virtual,2022-09-19 15:31:00,2022-09-19
11055,2022-08-26,NaT,KEMBER YASOLI,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,JEANCARLOS,ESPINOZA CASTRO,JEANCARLOS ESPINOZA CASTRO,48366616,963910668,Compro,NaN,NaN,2022-08-27
11166,2022-08-06,NaT,KEMBER YASOLI,Facebook_Leads,NaN,NaN,NaN,NaN,NaN,NaN,JIMMY AGUSTO,PARDO LAMA,JIMMY AGUSTO PARDO LAMA,44595380,969403152,Compro,NaN,NaN,2022-08-23
11609,2022-08-02,NaT,KEMBER YASOLI,Facebook_Leads,NaN,NaN,NaN,NaN,mañana,NaN,Jimmy Agusto,Pardo Lama,JIMMY AGUSTO PARDO LAMA,NaN,969403152,No interesado,NaN,NaN,2022-08-11
11960,2022-07-25,NaT,RAMIRO CIRO ERNESTO,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,DIEGO ALONSO,REYNA ZUÑIGA,DIEGO ALONSO REYNA ZUÑIGA,74128258,954133089,Compro,NaN,NaN,2022-07-28
11961,2022-07-25,NaT,RAMIRO CIRO ERNESTO,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,DIEGO ALONSO,REYNA ZUÑIGA,DIEGO ALONSO REYNA ZUÑIGA,74128258,954133089,Compro,NaN,NaN,2022-07-28
12452,2022-07-03,NaT,KEMBER YASOLI,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,jeancarlos,ESPINOZA CASTRO,JEANCARLOS ESPINOZA CASTRO,NaN,963910668,No interesado,NaN,NaN,2022-07-03
15274,2022-04-04,NaT,LUIS FERNANDO,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,JUAN CARLOS,MORALES RUIZ,JUAN CARLOS MORALES RUIZ,41423953,987560917,Compro,NaN,NaN,2022-04-07
15289,2022-04-04,NaT,LUIS FERNANDO,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,KARINA PAOLA,PALMA MENDOZA,KARINA PAOLA PALMA MENDOZA,44639599,998386176,Compro,NaN,NaN,2022-04-06
15435,2022-03-26,NaT,LUIS FERNANDO,Facebook_Leads,NaN,NaN,NaN,NaN,NaN,NaN,Karina Paola Palma,Mendoza,KARINA PAOLA PALMA MENDOZA,NaN,998386176,No Califica,NaN,NaN,2022-04-01
15441,2022-04-01,NaT,LUIS FERNANDO,Facebook_Leads,NaN,NaN,NaN,NaN,Tarde,NaN,Juan Carlos,Morales Ruiz,JUAN CARLOS MORALES RUIZ,NaN,987560917,No Califica,NaN,NaN,2022-04-01
15666,2022-02-10,NaT,MILAGROS DEL PILAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,MARTE CLOTARIO,MORALES GARCIA,MARTE CLOTARIO MORALES GARCIA,03649847,984849548,Compro,NaN,NaN,2022-02-10
15704,2022-01-26,NaT,MILAGROS DEL PILAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,MARTE CLOTARIO,MORALES GARCIA,MARTE CLOTARIO MORALES GARCIA,03649847,984849548,Compro,NaN,NaN,2022-01-26
15784,2021-12-18,NaT,RUBEN,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,PAUL ANTONIO,BRACAMONTE GUARDERAS,PAUL ANTONIO BRACAMONTE GUARDERAS,02891654,957225839,Compro,NaN,NaN,2021-12-18
15785,2021-12-18,NaT,RUBEN,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,PAUL ANTONIO,BRACAMONTE GUARDERAS,PAUL ANTONIO BRACAMONTE GUARDERAS,002891644,957225839,NaN,NaN,NaN,2021-12-18
17247,2021-03-25,NaT,OSCAR ANDRES,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,FELIX DE VALOIS,PERALTA FERRO,FELIX DE VALOIS PERALTA FERRO,41637446,988942346,NaN,NaN,NaN,2021-03-25
17248,2021-03-25,NaT,OSCAR ANDRES,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,FELIX DE VALOIS,PERALTA FERRO,FELIX DE VALOIS PERALTA FERRO,416374460,988942346,NaN,NaN,NaN,2021-03-25
17348,2021-03-11,NaT,MILAGROS DEL PILAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,DIEGO ALONSO,RUIZ MORANTE,DIEGO ALONSO RUIZ MORANTE,730689107,943208220,NaN,NaN,NaN,2021-03-11
17350,2021-03-11,NaT,MILAGROS DEL PILAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,DIEGO ALONSO,RUIZ MORANTE,DIEGO ALONSO RUIZ MORANTE,73068917,948901432,NaN,NaN,NaN,2021-03-11
17351,2021-03-11,NaT,MILAGROS DEL PILAR,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,DIEGO ALONSO,RUIZ MORANTE,DIEGO ALONSO RUIZ MORANTE,73068917,943208220,NaN,NaN,NaN,2021-03-11
17650,2021-02-20,NaT,ANDRES,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,YOO BIN,KIM,YOO BIN KIM,000454853,944663516,NaN,NaN,NaN,2021-02-20
17653,2021-02-20,NaT,ANDRES,Asesor,NaN,NaN,NaN,NaN,NaN,NaN,YOO BIN,KIM,YOO BIN KIM,00454853,944663516,Compro,NaN,NaN,2021-02-20

In [45]:
cmr_ventas_totales = mini_base_total.drop_duplicates(subset=['CLIENTE'])
#cmr_ventas_totales[cmr_ventas_totales['CLIENTE'].isin(cliente_duplicados_totales_cmr)]
cmr_ventas_totales['NIVEL DE INTERES'].fillna('Compro',inplace = True)
cmr_ventas_totales.shape[0]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\1541207001.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cmr_ventas_totales['NIVEL DE INTERES'].fillna('Compro',inplace = True)

926

In [46]:
cmr_ventas_totales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 926 entries, 88 to 17729
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA DE REGISTRO           926 non-null    datetime64[ns]
 1   HORA DE REGISTRO            166 non-null    datetime64[ns]
 2   VENDEDORES                  924 non-null    object
 3   ORIGEN                      926 non-null    object
 4   DIRECCION                   2 non-null      object
 5   QUE BUSCA                   1 non-null      object
 6   TIPO LOTES                  1 non-null      object
 7   PRECIOS                     1 non-null      object
 8   OBSERVACION                 59 non-null     object
 9   HORARIO DISPONIBLE          4 non-null      object
 10  nom                         926 non-null    object
 11  ape                         926 non-null    object
 12  CLIENTE                     926 non-null    object
 13  DNI                         926 non-null    object
 14  TELEFONO                    926 non-null    object
 15  NIVEL DE INTERES            926 non-null    object
 16  NOMBRE PROXIMO EVENTO       140 non-null    object
 17  FECHA PROXIMO EVENTO        140 non-null    object
 18  FECHA DE ULTIMA INTERACION  922 non-null    datetime64[ns]
dtypes: datetime64[ns](3), object(16)
memory usage: 144.7+ KB

In [47]:
cmr_ventas_totales = cmr_ventas_totales[['FECHA DE REGISTRO','HORA DE REGISTRO','VENDEDORES','CLIENTE','ORIGEN',
                                        'TELEFONO','NIVEL DE INTERES','NOMBRE PROXIMO EVENTO','FECHA PROXIMO EVENTO',
                                        'FECHA DE ULTIMA INTERACION']]

In [48]:
cmr_ventas_totales.rename(columns={'FECHA DE REGISTRO':'FECHA REGISTRO CMR','HORA DE REGISTRO':'HORA REGISTRO CMR','TELEFONO':'CELULAR CMR'},inplace = True)

In [49]:
cmr_ventas_totales

,FECHA REGISTRO CMR,HORA REGISTRO CMR,VENDEDORES,CLIENTE,ORIGEN,CELULAR CMR,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,FECHA DE ULTIMA INTERACION
88,2023-04-22,2023-05-02 18:00:43,OMAR,GASPAR SEVILLANO BARRETO,Facebook_Leads,946548975,Interesado Alto,NaN,NaN,2023-04-29
207,2022-09-30,2023-05-02 15:26:53,BRIAN ANDRE,CARLOS ANTONIO GONZALEZ RIOS,Asesor,990809904,Compro,Llamada,2023-04-27 12:23:00,2023-04-28
292,2023-04-21,2023-05-02 09:25:05,ROCIO,MARIELA SANDRA HUAMAN TORRES,Asesor,420728891584,No interesado,NaN,NaN,2023-04-27
308,2023-04-26,2023-05-02 17:49:29,LUIS FERNANDO,JOSE JORGE RONCAL NARVAEZ,Facebook_Leads,976961570,Compro,NaN,NaN,2023-04-26
447,2023-04-25,2023-05-02 11:20:39,RAMIRO CIRO ERNESTO,LUIS ALBERTO LEA TICONA,Asesor,953677750,Interesado Alto,Llamada,2023-04-29 11:20:00,2023-04-25
...,...,...,...,...,...,...,...,...,...,...
17717,2021-02-18,NaT,MILAGROS DEL PILAR,HAROLD ANDRES CAVERO PAREDES,Asesor,995279881,Compro,NaN,NaN,2021-02-18
17718,2022-03-23,NaT,LUIS FERNANDO,LIZ MILAGROS ZAGACETA COSAMALON,Asesor,942700620,Compro,NaN,NaN,NaT
17725,2022-04-06,NaT,FRANCISCO JAVIER,JULIO JUAN MIGUEL SALAZAR GARCIA,Asesor,999950637,Compro,NaN,NaN,NaT
17728,2022-04-07,NaT,RUBEN,PIERRE ARMANDO RODRIGUEZ FARIAS,Asesor,969973222,Compro,NaN,NaN,NaT
17729,2022-04-08,NaT,KENNY SMITH,JUAN MANUEL ANGASPILCO VASQUEZ,Asesor,980898067,Compro,NaN,NaN,NaT

#### Comprobar clientes

In [50]:
comprobar = cmr_ventas_totales['CLIENTE'].unique().tolist()
#ENMA ROSA DE LOS MILAGROS PIEDRA MAZA

In [51]:
dif =  set(cliente_excel_ventas)- set(comprobar)
dif

set()

### LEADS TOTAL

In [52]:
base_leads_total = leads_unidos[leads_unidos['CLIENTE'].isin(cliente_excel_ventas)]
base_leads_total.shape[0]

750

In [53]:
leads_cliente_repe = base_leads_total[base_leads_total['CLIENTE'].duplicated()]['CLIENTE'].tolist()

In [54]:
#base_leads_total[base_leads_total['CLIENTE'].isin(leads_cliente_repe)]

In [55]:
leads_ventas_totales = base_leads_total.drop_duplicates(subset=['CLIENTE'],keep='last')
#leads_ventas_totales[leads_ventas_totales['CLIENTE'].isin(leads_cliente_repe)]

In [56]:
print(leads_ventas_totales.shape[0])
#leads_ventas_totales

735

In [57]:
leads_ventas_totales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 735 entries, 480 to 1124
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FECHA REGISTRO  735 non-null    datetime64[ns]
 1   DNI             735 non-null    object
 2   CANAL           725 non-null    object
 3   CELULAR         735 non-null    object
 4   VENDEDOR        733 non-null    object
 5   DIRECCION       735 non-null    object
 6   CLIENTE         735 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 45.9+ KB

In [58]:
leads_ventas_totales = leads_ventas_totales[['FECHA REGISTRO','CANAL','VENDEDOR','DIRECCION','CLIENTE','CELULAR']]

In [59]:
leads_ventas_totales.rename(columns={'FECHA REGISTRO':'FECHA REGISTRO LEADS'},inplace = True)

In [60]:
leads_ventas_totales

,FECHA REGISTRO LEADS,CANAL,VENDEDOR,DIRECCION,CLIENTE,CELULAR
480,2022-11-23,Facebook,LUIS GERARDO RUIZ GIL,URB. ZAVALETA MZ B LT 12,FRANKLIN FREDDY DIAZ SERDA,987504351.0
0,2023-04-29,Lading Page,OMAR CAPUÑAY ROSALES,JR. BOLOGNESI 741,GASPAR SEVILLANO BARRETO,946548975
1,2023-04-26,NaN,LUIS FERNANDO DELGADO WONG,JR. LAS CASUARINAS 797,JOSE JORGE RONCAL NARVAEZ,976961570
2,2023-04-25,NaN,RAMIRO CIRO ERNESTO AVILES RUIZ,AV. BUGAMBILLAS 426,LUIS ALBERTO LEA TICONA,953677750
3,2023-04-25,Facebook,RAMIRO CIRO ERNESTO AVILES RUIZ,AV. BUGAMBILLAS 426,MARISOL LEA,953677750
...,...,...,...,...,...,...
1118,2021-02-19,Facebook,RUBEN MADRID SIANCAS,URB.SANTA ANA S-53,WILLIAM HERNAN CORDOVA CHINCHAY,986613464
1119,2021-02-18,Facebook,OSCAR ANDRES MIRANDA VEGA,AV. TALLANES S/N FUNDO VICTORIA,MARIO MARTIN VASQUEZ SARANGO,953621786
1120,2021-02-18,Facebook,KENNY SMITH SANCARRANCO BAZAN,AV. IRAZOLA MZ. C LT. 34 URB. MIRAFLORES,CIELO JANE HUAMAN ASTUDILLO,970280027
1122,2021-02-18,Facebook,MILAGROS DEL PILAR TRELLES DEZA,MZ. N1-23 URB. MIRAFLORES ETAPA II,HAROLD OSWALDO CAVERO PORTILLA,969640952
1124,2021-02-18,Facebook,MILAGROS DEL PILAR TRELLES DEZA,MZ. N1-23 URB. MIRAFLORES ETAPA II,HAROLD ANDRES CAVERO PAREDES,995279881

### Cruce de informacion entre CRM Y LEADS Total basado en ventas

In [61]:
cmr_leads_totales = pd.merge(leads_ventas_totales,cmr_ventas_totales, on='CLIENTE', how = 'right')

In [62]:
cmr_leads_totales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 926 entries, 0 to 925
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA REGISTRO LEADS        735 non-null    datetime64[ns]
 1   CANAL                       725 non-null    object
 2   VENDEDOR                    733 non-null    object
 3   DIRECCION                   735 non-null    object
 4   CLIENTE                     926 non-null    object
 5   CELULAR                     735 non-null    object
 6   FECHA REGISTRO CMR          926 non-null    datetime64[ns]
 7   HORA REGISTRO CMR           166 non-null    datetime64[ns]
 8   VENDEDORES                  924 non-null    object
 9   ORIGEN                      926 non-null    object
 10  CELULAR CMR                 926 non-null    object
 11  NIVEL DE INTERES            926 non-null    object
 12  NOMBRE PROXIMO EVENTO       140 non-null    object
 13  FECHA PROXIMO EVENTO        140 non-null    object
 14  FECHA DE ULTIMA INTERACION  922 non-null    datetime64[ns]
dtypes: datetime64[ns](4), object(11)
memory usage: 115.8+ KB

In [63]:
cmr_leads_totales = cmr_leads_totales.iloc[:,[0,4,3,1,9,8,10,6,7,11,12,13,5,14]]

In [64]:
cmr_leads_totales

,FECHA REGISTRO LEADS,CLIENTE,DIRECCION,CANAL,ORIGEN,VENDEDORES,CELULAR CMR,FECHA REGISTRO CMR,HORA REGISTRO CMR,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,CELULAR,FECHA DE ULTIMA INTERACION
0,2023-04-29,GASPAR SEVILLANO BARRETO,JR. BOLOGNESI 741,Lading Page,Facebook_Leads,OMAR,946548975,2023-04-22,2023-05-02 18:00:43,Interesado Alto,NaN,NaN,946548975,2023-04-29
1,2023-04-24,CARLOS ANTONIO GONZALEZ RIOS,URB SAN ISIDRO 2DA ETAPA MZ T1 LOTE 8,Facebook,Asesor,BRIAN ANDRE,990809904,2022-09-30,2023-05-02 15:26:53,Compro,Llamada,2023-04-27 12:23:00,990809904,2023-04-28
2,2023-04-22,MARIELA SANDRA HUAMAN TORRES,JR UNGARA MZA D3 LOTE 28URB MANGOMARCA,Referido de cliente,Asesor,ROCIO,420728891584,2023-04-21,2023-05-02 09:25:05,No interesado,NaN,NaN,420728891584,2023-04-27
3,2023-04-26,JOSE JORGE RONCAL NARVAEZ,JR. LAS CASUARINAS 797,NaN,Facebook_Leads,LUIS FERNANDO,976961570,2023-04-26,2023-05-02 17:49:29,Compro,NaN,NaN,976961570,2023-04-26
4,2023-04-25,LUIS ALBERTO LEA TICONA,AV. BUGAMBILLAS 426,NaN,Asesor,RAMIRO CIRO ERNESTO,953677750,2023-04-25,2023-05-02 11:20:39,Interesado Alto,Llamada,2023-04-29 11:20:00,953677750,2023-04-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921,2021-02-18,HAROLD ANDRES CAVERO PAREDES,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,995279881,2021-02-18,NaT,Compro,NaN,NaN,995279881,2021-02-18
922,2022-03-23,LIZ MILAGROS ZAGACETA COSAMALON,INT 101 C. V COVICORTI MZ LL LOTE 11,Referido de colaborador,Asesor,LUIS FERNANDO,942700620,2022-03-23,NaT,Compro,NaN,NaN,942700620,NaT
923,2022-04-06,JULIO JUAN MIGUEL SALAZAR GARCIA,CAL.HIPOLITO UNANUE NRO. 278 URB. LAS LEYENDAS,Referido de cliente,Asesor,FRANCISCO JAVIER,999950637,2022-04-06,NaT,Compro,NaN,NaN,999950637,NaT
924,2022-04-09,PIERRE ARMANDO RODRIGUEZ FARIAS,PIURA,Facebook,Asesor,RUBEN,969973222,2022-04-07,NaT,Compro,NaN,NaN,969973222,NaT
925,2022-04-08,JUAN MANUEL ANGASPILCO VASQUEZ,PASAJSE MONITOR HUASCAR 142 JESUS MARIA,Facebook,Asesor,KENNY SMITH,980898067,2022-04-08,NaT,Compro,NaN,NaN,980898067,NaT

### cruce de ventas con ventas

In [65]:
cmr_leads_ventas_totales = pd.merge(cmr_leads_totales,ventas_totales, on='CLIENTE', how = 'right')

In [66]:
cmr_leads_ventas_totales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1122 entries, 0 to 1121
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA REGISTRO LEADS        882 non-null    datetime64[ns]
 1   CLIENTE                     1122 non-null   object
 2   DIRECCION                   882 non-null    object
 3   CANAL                       869 non-null    object
 4   ORIGEN                      1122 non-null   object
 5   VENDEDORES                  1120 non-null   object
 6   CELULAR CMR                 1122 non-null   object
 7   FECHA REGISTRO CMR          1122 non-null   datetime64[ns]
 8   HORA REGISTRO CMR           207 non-null    datetime64[ns]
 9   NIVEL DE INTERES            1122 non-null   object
 10  NOMBRE PROXIMO EVENTO       164 non-null    object
 11  FECHA PROXIMO EVENTO        164 non-null    object
 12  CELULAR                     882 non-null    object
 13  FECHA DE ULTIMA INTERACION  1117 non-null   datetime64[ns]
 14  FECHA VENTA                 1122 non-null   datetime64[ns]
 15  HORA VENTA                  1122 non-null   datetime64[ns]
 16  DNI                         1122 non-null   int64
 17  VENDEDOR                    1122 non-null   object
 18  CODIGO                      1122 non-null   object
 19  LOTE                        1122 non-null   object
 20  ubicacion                   1122 non-null   object
 21  PRECIO                      1122 non-null   float64
 22  PrecioCliente               1122 non-null   float64
 23  N CUOTAS                    1122 non-null   int64
 24  ESTADO VENTA                1122 non-null   object
 25  FechaDeposito               1116 non-null   object
 26  contrato                    981 non-null    float64
 27  fecha_contrato              981 non-null    object
 28  formapago                   1122 non-null   object
dtypes: datetime64[ns](6), float64(3), int64(2), object(18)
memory usage: 263.0+ KB

In [67]:
asesor= ['Referido de colaborador','Referido de cliente','Referido','Convenio Colegio Medico','Convenio Colegio de Ingenieros',
        'Convenio Colegio de Obstetras','Volanteo','EMPRESA','Referido Valle','Activación empresas','convenio colegio odontólogos',
        'Convenio Colegio de Enfermeros']
origen_Pasivo=['Panel Publicitario','Paneles','Masivo','Oficina','Diario','Television','Sala de ventas','Radio']
facebook_Leads=['Facebook','Instagram','Facebook_Leads']
call_Center=['WhatsApp','Messenger','ManyChat WhatsApp','ManyChat Facebook','Call Center']
lading_Page=['Lading Page','Pagina Web','Pagina_Web']

In [68]:
cmr_leads_ventas_totales['ORIGEN_SINCERADO'] = np.where((cmr_leads_ventas_totales['CANAL'].isin(asesor)),'Asesor',
               np.where((cmr_leads_ventas_totales['CANAL'].isin(origen_Pasivo)),'Origen_Pasivo',
                       np.where((cmr_leads_ventas_totales['CANAL'].isin(facebook_Leads)),'Facebook_Leads',
                                np.where((cmr_leads_ventas_totales['CANAL'].isin(call_Center)),'Call_Center',
                                        np.where((cmr_leads_ventas_totales['CANAL'].isin(lading_Page)),'Landing_Page',cmr_leads_ventas_totales['ORIGEN']
                                                )))))

In [69]:
cmr_leads_ventas_totales['ORIGEN_SINCERADO'] = cmr_leads_ventas_totales['ORIGEN_SINCERADO'].str.replace('Call Center','Call_Center')
cmr_leads_ventas_totales['ORIGEN_SINCERADO'] = cmr_leads_ventas_totales['ORIGEN_SINCERADO'].str.replace('Pagina_Web','Landing_Page')

In [70]:
tabla_origen_sincerado = cmr_leads_ventas_totales['ORIGEN_SINCERADO'].value_counts().to_frame('ORIGEN_SINCERADO')
tabla_origen_sincerado

                ORIGEN_SINCERADO
Asesor                       552
Facebook_Leads               483
Origen_Pasivo                 36
Call_Center                   28
Landing_Page                  23

In [71]:
tabla_origen = cmr_leads_ventas_totales['ORIGEN'].value_counts().to_frame('ORIGEN')
tabla_origen

                    ORIGEN
Asesor                 915
Facebook_Leads         125
Call Center             66
Pagina_Web              15
ManyChat_Instagram       1

In [72]:
print('TENEMOS UN TOTAL DE REGISTROS VACIOS EN CANAL DE:',cmr_leads_ventas_totales['CANAL'].isnull().sum() )
print('TENEMOS UN TOTAL DE REGISTROS EN CANAL DE:',cmr_leads_ventas_totales['CANAL'].value_counts().sum() )
tabla_leads = cmr_leads_ventas_totales['CANAL'].value_counts().to_frame('Totales').reset_index().rename(columns={'index':'Canales'})
tabla_leads

TENEMOS UN TOTAL DE REGISTROS VACIOS EN CANAL DE: 253
TENEMOS UN TOTAL DE REGISTROS EN CANAL DE: 869

                           Canales  Totales
0                         Facebook      434
1          Referido de colaborador      146
2              Referido de cliente      103
3                         Referido       70
4          Convenio Colegio Medico       30
5                          Oficina       14
6                      Lading Page        8
7                        Instagram        8
8               Panel Publicitario        7
9                       Pagina Web        7
10                         EMPRESA        6
11                         Paneles        6
12                        WhatsApp        4
13               ManyChat WhatsApp        3
14   Convenio Colegio de Obstetras        3
15                  Sala de ventas        3
16                Referido Directo        2
17                          Masivo        2
18                  Referido Valle        2
19  Convenio Colegio de Ingenieros        2
20  Convenio Colegio de Enfermeros        2
21                          Diario        2
22                        Volanteo        1
23              Activacion Empresa        1
24             Activación empresas        1
25                           Radio        1
26                      Television        1

In [73]:
direcciones = cmr_leads_ventas_totales['DIRECCION'].value_counts().to_frame('N_Veces').reset_index().rename(columns={'index':'Direcciones'})

### GUARDAR INFORMACION HISTORICO -Power BI

In [74]:
cmr_leads_ventas_totales2 = cmr_leads_ventas_totales[(cmr_leads_ventas_totales['FECHA VENTA']<='2023-04-30')]

In [116]:
writer2 = pd.ExcelWriter('Cruce_Info_Global.xlsx')

In [117]:
#cmr_leads_ventas_totales2.to_excel(writer2, sheet_name="HISTORICO_LEADS_VENTAS_CMR", index=False) #REVISALOOOOOOOOOO
#direcciones.to_excel(writer2, sheet_name="DIRECCIONES", index=False)
#tabla_origen_sincerado.to_excel(writer2, sheet_name="Origen_sincerado")
#tabla_origen.to_excel(writer2, sheet_name="Origen")
#tabla_leads.to_excel(writer2, sheet_name="Leads", index=False)

In [118]:
#writer2.save()
#writer2.close()

C:\Users\ASUS\anaconda3\lib\site-packages\xlsxwriter\workbook.py:339: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [78]:
cmr_leads_ventas_totales['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    762
VENCIDA           149
RESOLUCIÓN         77
DEVOLUCION C.I     48
DESISTIMIENTO      47
PRE-RESUELTO       32
SEPARACION          7
Name: ESTADO VENTA, dtype: int64

In [79]:
cmr_leads_ventas_totales2['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    762
VENCIDA           149
RESOLUCIÓN         77
DEVOLUCION C.I     48
DESISTIMIENTO      47
PRE-RESUELTO       32
SEPARACION          7
Name: ESTADO VENTA, dtype: int64

In [80]:
cmr_leads_ventas_totales2.shape

(1122, 30)

## REPORTE DE LOTES

### VER COMO SE AGREGA AL BI PARA MKT

In [81]:
reporte_lotes = pd.read_excel('Mayo 02_2023\Reporte_lotes.xlsx',header=2,)
reporte_lotes.head(2)

,Zona,Proyecto,ubicacion,Nombre,Area Casa,Area Lote,Precio,Precio F.,Valor Cuota,Estado Lote,Estado Gerencia
0,PIURA,TAHITI BLUE - ETAPA 1,ESQUINA,EA01,0,250.0,39000.0,39000.0,NaN,PAGANDO,Habilitado
1,PIURA,TAHITI BLUE - ETAPA 1,FRENTE A CALLE,EA02,0,250.0,30000.0,30000.0,NaN,PAGANDO,Habilitado

In [82]:
reporte_lotes.rename(columns={'Nombre':'LOTE','ubicacion':'UBICACION_LOTE'},inplace=True)
reporte_lotes.drop(columns=['Area Casa','Estado Lote','Estado Gerencia','Zona'],inplace=True)

In [83]:
conexion_lotes = pd.merge(cmr_leads_ventas_totales2,reporte_lotes, on = 'LOTE', how = 'left')

In [84]:
conexion_lotes

,FECHA REGISTRO LEADS,CLIENTE,DIRECCION,CANAL,ORIGEN,VENDEDORES,CELULAR CMR,FECHA REGISTRO CMR,HORA REGISTRO CMR,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,CELULAR,FECHA DE ULTIMA INTERACION,FECHA VENTA,HORA VENTA,DNI,VENDEDOR,CODIGO,LOTE,ubicacion,PRECIO,PrecioCliente,N CUOTAS,ESTADO VENTA,FechaDeposito,contrato,fecha_contrato,formapago,ORIGEN_SINCERADO,Proyecto,UBICACION_LOTE,Area Lote,Precio,Precio F.,Valor Cuota
0,2023-04-29,GASPAR SEVILLANO BARRETO,JR. BOLOGNESI 741,Lading Page,Facebook_Leads,OMAR,946548975,2023-04-22,2023-05-02 18:00:43,Interesado Alto,NaN,NaN,946548975,2023-04-29,2023-04-29,2023-05-02 11:29:18,42309969,OMAR CAPUÑAY ROSALES,VN0001556,AG06,ESQUINA - FRENTE A ALAMEDA,253854.81,253854.81,158,SEPARACION,2023-04-27,NaN,NaN,FINANCIADO,Landing_Page,TAHITI BLUE - ETAPA 4,ESQUINA - FRENTE A ALAMEDA,569.82,282060.90,282060.90,4063.89
1,2023-04-26,JOSE JORGE RONCAL NARVAEZ,JR. LAS CASUARINAS 797,NaN,Facebook_Leads,LUIS FERNANDO,976961570,2023-04-26,2023-05-02 17:49:29,Compro,NaN,NaN,976961570,2023-04-26,2023-04-26,2023-05-02 17:55:17,26644425,LUIS FERNANDO DELGADO WONG,VN0001555,BJ26,FRENTE A PARQUE,60275.24,60275.24,168,PAGANDO CUOTAS,2023-04-26,1338.0,2023-04-26,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 8,FRENTE A PARQUE,304.73,66972.49,66972.49,NaN
2,2023-04-25,LUIS ALBERTO LEA TICONA,AV. BUGAMBILLAS 426,NaN,Asesor,RAMIRO CIRO ERNESTO,953677750,2023-04-25,2023-05-02 11:20:39,Interesado Alto,Llamada,2023-04-29 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:40:07,44328064,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001554,DK15,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Asesor,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37
3,2023-04-25,MARISOL LEA,AV. BUGAMBILLAS 426,Facebook,Facebook_Leads,RAMIRO CIRO ERNESTO,953677750,2023-04-24,2023-05-02 11:43:15,Interesado Alto,Llamada,2023-04-26 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:36:08,417925,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001553,DK14,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37
4,2023-04-24,CARLOS ANTONIO GONZALEZ RIOS,URB SAN ISIDRO 2DA ETAPA MZ T1 LOTE 8,Facebook,Asesor,BRIAN ANDRE,990809904,2022-09-30,2023-05-02 15:26:53,Compro,Llamada,2023-04-27 12:23:00,990809904,2023-04-28,2023-04-24,2023-05-02 12:31:33,18161689,BRIAN ANDRE MONDRAGON FLORES,VN0001552,DL16,ESQUINA,56421.18,56421.18,158,PAGANDO CUOTAS,2023-04-28,1340.0,2023-04-28,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,ESQUINA,273.36,62690.20,62690.20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:50,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000010,EI28,ESQUINA,34387.50,34387.50,120,PAGANDO CUOTAS,2021-02-19,13.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,ESQUINA,275.10,34387.50,34387.50,NaN
1118,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:32,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000009,EI27,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,12.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN
1119,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:32:08,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000008,EI24,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,11.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN
1120,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:31:58,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000007,EI23,JARDIN,30471.00,30471.00,120,PAGANDO CUOTAS,2021-02-19,10.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,290.20,30471.00,30471.00,NaN
1121,2021-02-18,CIELO JANE HUAMAN ASTUDILLO,AV. IRAZOLA MZ. C LT. 34 URB. MIRAFLORES,Facebook,Asesor,LUIS FERNANDO,970280027,2021-02-18,NaT,Compro,NaN,NaN,970280027,2021-02-18,2021-02-18,2023-05-02 16:40:09,9920379,KENNY SMITH SANCARRANCO BAZAN,VN0000004,EE25,JARDIN,27394.50,27394.50,120,PAGANDO CUOTAS,2021-02-18,1.0,2021-02-18,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,260.90,27394.50,27394.50,NaN

## REVISAR ESTE INPUT PARA DE CRUZAR DATA

In [85]:
cmr_leads_ventas_totales2 = conexion_lotes

## REVISAR DATA DE REPORTE

In [86]:
reporte_fecha = pd.read_excel('Mayo 02_2023/Reporte_todas_las_ventas_Reporte.xlsx',header=2,
                              parse_dates=['FECHA NACIMIENTO','FECHA VENTA'])

In [87]:
reporte_fecha['CLIENTE'] = reporte_fecha['CLIENTE'].str.replace('EMMA ROSA DE LOS MILAGROS PIEDRA MAZA','ENMA ROSA DE LOS MILAGROS PIEDRA MAZA')

In [88]:
reporte_fecha = reporte_fecha[reporte_fecha['ESTADO VENTA']!='ANULADA']

In [89]:
reporteRx = reporte_fecha.drop(columns=['CONYUGUE','DNI CONYUGUE','ESTADO CIVIL CONYUGUE','TELEFONO 1','TELEFONO 2'])

In [90]:
reporteRx['CLIENTE'] = reporteRx['CLIENTE'].str.strip().str.upper()

In [91]:
reporteRx['CLIENTE'] = reporteRx['CLIENTE'].str.replace('  ',' ')

In [91]:
# COLOCAR LA FECHA

In [92]:
reporteR = reporteRx[reporteRx['FECHA VENTA']<='2023-04-30']

In [93]:
reporteR[reporteR['FECHA VENTA']<='2023-04-30']['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    760
VENCIDA           146
RESOLUCIÓN         77
DEVOLUCION C.I     48
DESISTIMIENTO      47
PRE-RESUELTO       32
SEPARACION          7
Name: ESTADO VENTA, dtype: int64

In [94]:
reporteR.rename(columns={'DNI':'DNI_R','CANAL':'CANAL_R','ORIGEN':'ORIGEN_R','CELULAR':'CELULAR_R'},inplace=True)

In [95]:
reporteR

,CLIENTE,DNI_R,ESTADO CIVIL,FECHA NACIMIENTO,EDAD,PROFESION,DEPARTAMENTO,PROVINCIA,DISTRITO,MOTIVO COMPRA,CANAL_R,ORIGEN_R,MEDIO DE CAPTACION,ASESOR,ETAPA,UBICACION,LOTE,AREA,PRECIO,TASA,CUOTAS,DESCUENTO,PRECIO FINAL,FINANCIAMIENTO,FECHA VENTA,ESTADO VENTA,MONTO FINAL,TOTAL PAGANDO,PORCENTAJE P,CORREO,CELULAR_R
0,GASPAR SEVILLANO BARRETO,42309969,SOLTERO,1984-04-10,39.0,NaN,Ancash,Santa,Chimbote,NaN,Community,Facebook_Leads,Lading Page,OMAR CAPUÑAY ROSALES,TAHITI BLUE - ETAPA 4,ESQUINA - FRENTE A ALAMEDA,AG06,569.82,282060.90,10%,158,28206.09,253854.81,FINANCIADO,2023-04-29,SEPARACION,410412.86,27.00,0.01,GSB.SEVILLA@GMAIL.COM,946548975
1,JOSE JORGE RONCAL NARVAEZ,26644425,CASADO,1972-03-19,51.0,NaN,Cajamarca,Cajamarca,Cajamarca,Inversión,Community,Facebook_Leads,Facebook,LUIS FERNANDO DELGADO WONG,TAHITI BLUE - ETAPA 8,FRENTE A PARQUE,BJ26,304.73,66972.49,15%,168,6697.25,60275.24,FINANCIADO,2023-04-26,PAGANDO CUOTAS,118576.78,280.00,0.24,PPRONCALN@HOTMAIL.COM,976961570
2,LUIS ALBERTO LEA TICONA,44328064,SOLTERO,1987-04-05,36.0,NaN,Tacna,Tacna,Pocollay,Inversión,Community,Asesor,Referido de colaborador,RAMIRO CIRO ERNESTO AVILES RUIZ,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,DK15,250.00,47777.50,15%,158,4777.75,42999.75,FINANCIADO,2023-04-25,SEPARACION,84591.52,50.00,0.06,LUISLEA1987@GMAIL.COM,953677750
3,MARISOL LEA,417925,SOLTERO,1966-09-12,57.0,NaN,Tacna,Tacna,Pocollay,Inversión,Community,Facebook_Leads,Facebook,RAMIRO CIRO ERNESTO AVILES RUIZ,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,DK14,250.00,47777.50,15%,158,4777.75,42999.75,FINANCIADO,2023-04-25,SEPARACION,84591.52,50.00,0.06,SOLYMAR_LT@HOTMAIL.COM,953677750
4,CARLOS ANTONIO GONZALEZ RIOS,18161689,CASADO,1988-08-08,35.0,NaN,La Libertad,Trujillo,Trujillo,Vivienda,Cita Asesor,Asesor,Referido,BRIAN ANDRE MONDRAGON FLORES,TAHITI BLUE - ETAPA 2,ESQUINA,DL16,273.36,62690.20,15%,158,6269.02,56421.18,FINANCIADO,2023-04-24,PAGANDO CUOTAS,110995.19,403.01,0.36,CALIN4102@HOTMAIL.COM,990809904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,HAROLD OSWALDO CAVERO PORTILLA,2667241,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,ESQUINA,EI28,275.10,34387.50,15%,120,0.00,34387.50,FINANCIADO,2021-02-19,PAGANDO CUOTAS,64214.42,12307.76,19.17,HAROLDCAVERO@GMAIL.COM,969640952
1531,HAROLD OSWALDO CAVERO PORTILLA,2667241,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,EI27,325.10,34135.50,15%,120,0.00,34135.50,FINANCIADO,2021-02-19,PAGANDO CUOTAS,63743.93,11686.40,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1532,HAROLD OSWALDO CAVERO PORTILLA,2667241,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,EI24,325.10,34135.50,15%,120,0.00,34135.50,FINANCIADO,2021-02-19,PAGANDO CUOTAS,63743.93,11686.40,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1533,HAROLD OSWALDO CAVERO PORTILLA,2667241,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,EI23,290.20,30471.00,15%,120,0.00,30471.00,FINANCIADO,2021-02-19,PAGANDO CUOTAS,56900.63,10431.74,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1536,CIELO JANE HUAMAN ASTUDILLO,9920379,CASADO,1968-05-03,55.0,INDEPENDIENTE,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,KENNY SMITH SANCARRANCO BAZAN,TAHITI BLUE - ETAPA 1,JARDIN,EE25,260.90,27394.50,15%,120,0.00,27394.50,FINANCIADO,2021-02-18,PAGANDO CUOTAS,51155.93,11510.10,22.50,NaN,970280027

In [96]:
cmr_leads_ventas_totales2

,FECHA REGISTRO LEADS,CLIENTE,DIRECCION,CANAL,ORIGEN,VENDEDORES,CELULAR CMR,FECHA REGISTRO CMR,HORA REGISTRO CMR,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,CELULAR,FECHA DE ULTIMA INTERACION,FECHA VENTA,HORA VENTA,DNI,VENDEDOR,CODIGO,LOTE,ubicacion,PRECIO,PrecioCliente,N CUOTAS,ESTADO VENTA,FechaDeposito,contrato,fecha_contrato,formapago,ORIGEN_SINCERADO,Proyecto,UBICACION_LOTE,Area Lote,Precio,Precio F.,Valor Cuota
0,2023-04-29,GASPAR SEVILLANO BARRETO,JR. BOLOGNESI 741,Lading Page,Facebook_Leads,OMAR,946548975,2023-04-22,2023-05-02 18:00:43,Interesado Alto,NaN,NaN,946548975,2023-04-29,2023-04-29,2023-05-02 11:29:18,42309969,OMAR CAPUÑAY ROSALES,VN0001556,AG06,ESQUINA - FRENTE A ALAMEDA,253854.81,253854.81,158,SEPARACION,2023-04-27,NaN,NaN,FINANCIADO,Landing_Page,TAHITI BLUE - ETAPA 4,ESQUINA - FRENTE A ALAMEDA,569.82,282060.90,282060.90,4063.89
1,2023-04-26,JOSE JORGE RONCAL NARVAEZ,JR. LAS CASUARINAS 797,NaN,Facebook_Leads,LUIS FERNANDO,976961570,2023-04-26,2023-05-02 17:49:29,Compro,NaN,NaN,976961570,2023-04-26,2023-04-26,2023-05-02 17:55:17,26644425,LUIS FERNANDO DELGADO WONG,VN0001555,BJ26,FRENTE A PARQUE,60275.24,60275.24,168,PAGANDO CUOTAS,2023-04-26,1338.0,2023-04-26,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 8,FRENTE A PARQUE,304.73,66972.49,66972.49,NaN
2,2023-04-25,LUIS ALBERTO LEA TICONA,AV. BUGAMBILLAS 426,NaN,Asesor,RAMIRO CIRO ERNESTO,953677750,2023-04-25,2023-05-02 11:20:39,Interesado Alto,Llamada,2023-04-29 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:40:07,44328064,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001554,DK15,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Asesor,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37
3,2023-04-25,MARISOL LEA,AV. BUGAMBILLAS 426,Facebook,Facebook_Leads,RAMIRO CIRO ERNESTO,953677750,2023-04-24,2023-05-02 11:43:15,Interesado Alto,Llamada,2023-04-26 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:36:08,417925,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001553,DK14,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37
4,2023-04-24,CARLOS ANTONIO GONZALEZ RIOS,URB SAN ISIDRO 2DA ETAPA MZ T1 LOTE 8,Facebook,Asesor,BRIAN ANDRE,990809904,2022-09-30,2023-05-02 15:26:53,Compro,Llamada,2023-04-27 12:23:00,990809904,2023-04-28,2023-04-24,2023-05-02 12:31:33,18161689,BRIAN ANDRE MONDRAGON FLORES,VN0001552,DL16,ESQUINA,56421.18,56421.18,158,PAGANDO CUOTAS,2023-04-28,1340.0,2023-04-28,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,ESQUINA,273.36,62690.20,62690.20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:50,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000010,EI28,ESQUINA,34387.50,34387.50,120,PAGANDO CUOTAS,2021-02-19,13.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,ESQUINA,275.10,34387.50,34387.50,NaN
1118,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:32,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000009,EI27,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,12.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN
1119,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:32:08,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000008,EI24,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,11.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN
1120,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:31:58,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000007,EI23,JARDIN,30471.00,30471.00,120,PAGANDO CUOTAS,2021-02-19,10.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,290.20,30471.00,30471.00,NaN
1121,2021-02-18,CIELO JANE HUAMAN ASTUDILLO,AV. IRAZOLA MZ. C LT. 34 URB. MIRAFLORES,Facebook,Asesor,LUIS FERNANDO,970280027,2021-02-18,NaT,Compro,NaN,NaN,970280027,2021-02-18,2021-02-18,2023-05-02 16:40:09,9920379,KENNY SMITH SANCARRANCO BAZAN,VN0000004,EE25,JARDIN,27394.50,27394.50,120,PAGANDO CUOTAS,2021-02-18,1.0,2021-02-18,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,260.90,27394.50,27394.50,NaN

In [97]:
clientes_cruce = cmr_leads_ventas_totales2['CLIENTE'].unique().tolist()

In [98]:
clientes_reporte = reporteR['CLIENTE'].unique().tolist()

In [99]:
diferencia_cliente = set(clientes_cruce)-set(clientes_reporte)
diferencia_cliente

{'DAVID ERICK SANCHEZ ROJAS',
 'ISRRAEL MARTINEZ TALLEDO',
 'KETTY CRISPIN HUACHUA',
 'MARIA PATRICIA RODRIGUEZ KONG',
 'PAUL ANTONINNI SARMIENTO ROMERO'}

In [100]:
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.upper()
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.upper()
reporteR['DEPARTAMENTO'] = reporteR['DEPARTAMENTO'].str.upper()

In [101]:
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('MORROPÓN','MORROPON')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('PROV. CONST. DEL CALLAO','CALLAO')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('CONCEPCIÓN','CONCEPCION')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('VIRÚ','VIRU')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('CONTUMAZÁ','CONTUMAZA')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('CELENDÍN','CELENDIN')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('CAMANÁ','CAMANA')
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('LA CONVENCIÓN','LA CONVENCION')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13584\2759272547.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.replace('PROV. CONST. DEL CALLAO','CALLAO')

In [102]:
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.replace('BRENA','BREÑA')
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.replace('LOS BANOS DEL INCA','LOS BAÑOS DEL INCA')
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.replace('PARINAS','PARIÑAS')
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.replace('VEINTISEIS DE OCTUBRE','PIURA')
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.replace('PUEBLO LIBRE','CARABAYLLO')

In [103]:
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].str.title()
reporteR['DISTRITO'] = reporteR['DISTRITO'].str.title()
reporteR['DEPARTAMENTO'] = reporteR['DEPARTAMENTO'].str.title()

In [104]:
reporteR['PROVINCIA'] = reporteR['PROVINCIA'].fillna('Piura')
reporteR['DISTRITO'] = reporteR['DISTRITO'].fillna('Piura')

In [105]:
#reporteR['TASA'] = reporteR['TASA'].str.replace('%','15%')

In [106]:
reporteR['TASA'].value_counts()

15%     1090
5%        16
7.5%       7
10%        1
0          1
%          1
1%         1
Name: TASA, dtype: int64

# DATA PARA POWER BI

In [115]:
#reporteR.to_excel('Reporte_Ventas.xlsx', index=False)

## CRUCE DE DATA GLOBAL Y REPORTE

In [107]:
data_global = pd.merge(cmr_leads_ventas_totales2,reporteR, on=['CLIENTE','ESTADO VENTA','LOTE','FECHA VENTA'], how = 'left' )

In [108]:
data_global

,FECHA REGISTRO LEADS,CLIENTE,DIRECCION,CANAL,ORIGEN,VENDEDORES,CELULAR CMR,FECHA REGISTRO CMR,HORA REGISTRO CMR,NIVEL DE INTERES,NOMBRE PROXIMO EVENTO,FECHA PROXIMO EVENTO,CELULAR,FECHA DE ULTIMA INTERACION,FECHA VENTA,HORA VENTA,DNI,VENDEDOR,CODIGO,LOTE,ubicacion,PRECIO_x,PrecioCliente,N CUOTAS,ESTADO VENTA,FechaDeposito,contrato,fecha_contrato,formapago,ORIGEN_SINCERADO,Proyecto,UBICACION_LOTE,Area Lote,Precio,Precio F.,Valor Cuota,DNI_R,ESTADO CIVIL,FECHA NACIMIENTO,EDAD,PROFESION,DEPARTAMENTO,PROVINCIA,DISTRITO,MOTIVO COMPRA,CANAL_R,ORIGEN_R,MEDIO DE CAPTACION,ASESOR,ETAPA,UBICACION,AREA,PRECIO_y,TASA,CUOTAS,DESCUENTO,PRECIO FINAL,FINANCIAMIENTO,MONTO FINAL,TOTAL PAGANDO,PORCENTAJE P,CORREO,CELULAR_R
0,2023-04-29,GASPAR SEVILLANO BARRETO,JR. BOLOGNESI 741,Lading Page,Facebook_Leads,OMAR,946548975,2023-04-22,2023-05-02 18:00:43,Interesado Alto,NaN,NaN,946548975,2023-04-29,2023-04-29,2023-05-02 11:29:18,42309969,OMAR CAPUÑAY ROSALES,VN0001556,AG06,ESQUINA - FRENTE A ALAMEDA,253854.81,253854.81,158,SEPARACION,2023-04-27,NaN,NaN,FINANCIADO,Landing_Page,TAHITI BLUE - ETAPA 4,ESQUINA - FRENTE A ALAMEDA,569.82,282060.90,282060.90,4063.89,42309969.0,SOLTERO,1984-04-10,39.0,NaN,Ancash,Santa,Chimbote,NaN,Community,Facebook_Leads,Lading Page,OMAR CAPUÑAY ROSALES,TAHITI BLUE - ETAPA 4,ESQUINA - FRENTE A ALAMEDA,569.82,282060.90,10%,158.0,28206.09,253854.81,FINANCIADO,410412.86,27.00,0.01,GSB.SEVILLA@GMAIL.COM,946548975
1,2023-04-26,JOSE JORGE RONCAL NARVAEZ,JR. LAS CASUARINAS 797,NaN,Facebook_Leads,LUIS FERNANDO,976961570,2023-04-26,2023-05-02 17:49:29,Compro,NaN,NaN,976961570,2023-04-26,2023-04-26,2023-05-02 17:55:17,26644425,LUIS FERNANDO DELGADO WONG,VN0001555,BJ26,FRENTE A PARQUE,60275.24,60275.24,168,PAGANDO CUOTAS,2023-04-26,1338.0,2023-04-26,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 8,FRENTE A PARQUE,304.73,66972.49,66972.49,NaN,26644425.0,CASADO,1972-03-19,51.0,NaN,Cajamarca,Cajamarca,Cajamarca,Inversión,Community,Facebook_Leads,Facebook,LUIS FERNANDO DELGADO WONG,TAHITI BLUE - ETAPA 8,FRENTE A PARQUE,304.73,66972.49,15%,168.0,6697.25,60275.24,FINANCIADO,118576.78,280.00,0.24,PPRONCALN@HOTMAIL.COM,976961570
2,2023-04-25,LUIS ALBERTO LEA TICONA,AV. BUGAMBILLAS 426,NaN,Asesor,RAMIRO CIRO ERNESTO,953677750,2023-04-25,2023-05-02 11:20:39,Interesado Alto,Llamada,2023-04-29 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:40:07,44328064,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001554,DK15,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Asesor,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37,44328064.0,SOLTERO,1987-04-05,36.0,NaN,Tacna,Tacna,Pocollay,Inversión,Community,Asesor,Referido de colaborador,RAMIRO CIRO ERNESTO AVILES RUIZ,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,15%,158.0,4777.75,42999.75,FINANCIADO,84591.52,50.00,0.06,LUISLEA1987@GMAIL.COM,953677750
3,2023-04-25,MARISOL LEA,AV. BUGAMBILLAS 426,Facebook,Facebook_Leads,RAMIRO CIRO ERNESTO,953677750,2023-04-24,2023-05-02 11:43:15,Interesado Alto,Llamada,2023-04-26 11:20:00,953677750,2023-04-25,2023-04-25,2023-05-02 11:36:08,417925,RAMIRO CIRO ERNESTO AVILES RUIZ,VN0001553,DK14,FRENTE A CALLE,42999.75,42999.75,158,SEPARACION,2023-04-24,NaN,NaN,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,47777.50,688.37,417925.0,SOLTERO,1966-09-12,57.0,NaN,Tacna,Tacna,Pocollay,Inversión,Community,Facebook_Leads,Facebook,RAMIRO CIRO ERNESTO AVILES RUIZ,TAHITI BLUE - ETAPA 2,FRENTE A CALLE,250.00,47777.50,15%,158.0,4777.75,42999.75,FINANCIADO,84591.52,50.00,0.06,SOLYMAR_LT@HOTMAIL.COM,953677750
4,2023-04-24,CARLOS ANTONIO GONZALEZ RIOS,URB SAN ISIDRO 2DA ETAPA MZ T1 LOTE 8,Facebook,Asesor,BRIAN ANDRE,990809904,2022-09-30,2023-05-02 15:26:53,Compro,Llamada,2023-04-27 12:23:00,990809904,2023-04-28,2023-04-24,2023-05-02 12:31:33,18161689,BRIAN ANDRE MONDRAGON FLORES,VN0001552,DL16,ESQUINA,56421.18,56421.18,158,PAGANDO CUOTAS,2023-04-28,1340.0,2023-04-28,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 2,ESQUINA,273.36,62690.20,62690.20,NaN,18161689.0,CASADO,1988-08-08,35.0,NaN,La Libertad,Trujillo,Trujillo,Vivienda,Cita Asesor,Asesor,Referido,BRIAN ANDRE MONDRAGON FLORES,TAHITI BLUE - ETAPA 2,ESQUINA,273.36,62690.20,15%,158.0,6269.02,56421.18,FINANCIADO,110995.19,403.01,0.36,CALIN4102@HOTMAIL.COM,990809904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:50,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000010,EI28,ESQUINA,34387.50,34387.50,120,PAGANDO CUOTAS,2021-02-19,13.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,ESQUINA,275.10,34387.50,34387.50,NaN,2667241.0,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,ESQUINA,275.10,34387.50,15%,120.0,0.00,34387.50,FINANCIADO,64214.42,12307.76,19.17,HAROLDCAVERO@GMAIL.COM,969640952
1118,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:33:32,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000009,EI27,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,12.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN,2667241.0,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,15%,120.0,0.00,34135.50,FINANCIADO,63743.93,11686.40,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1119,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:32:08,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000008,EI24,JARDIN,34135.50,34135.50,120,PAGANDO CUOTAS,2021-02-19,11.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,34135.50,NaN,2667241.0,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,325.10,34135.50,15%,120.0,0.00,34135.50,FINANCIADO,63743.93,11686.40,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1120,2021-02-18,HAROLD OSWALDO CAVERO PORTILLA,MZ. N1-23 URB. MIRAFLORES ETAPA II,Facebook,Asesor,MILAGROS DEL PILAR,969640952,2021-02-18,NaT,Compro,NaN,NaN,969640952,2021-02-18,2021-02-19,2023-05-02 09:31:58,2667241,MILAGROS DEL PILAR TRELLES DEZA,VN0000007,EI23,JARDIN,30471.00,30471.00,120,PAGANDO CUOTAS,2021-02-19,10.0,2021-02-19,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,290.20,30471.00,30471.00,NaN,2667241.0,CASADO,1960-03-06,63.0,GERENTE GENERAL,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,MILAGROS DEL PILAR TRELLES DEZA,TAHITI BLUE - ETAPA 1,JARDIN,290.20,30471.00,15%,120.0,0.00,30471.00,FINANCIADO,56900.63,10431.74,18.33,HAROLDCAVERO@GMAIL.COM,969640952
1121,2021-02-18,CIELO JANE HUAMAN ASTUDILLO,AV. IRAZOLA MZ. C LT. 34 URB. MIRAFLORES,Facebook,Asesor,LUIS FERNANDO,970280027,2021-02-18,NaT,Compro,NaN,NaN,970280027,2021-02-18,2021-02-18,2023-05-02 16:40:09,9920379,KENNY SMITH SANCARRANCO BAZAN,VN0000004,EE25,JARDIN,27394.50,27394.50,120,PAGANDO CUOTAS,2021-02-18,1.0,2021-02-18,FINANCIADO,Facebook_Leads,TAHITI BLUE - ETAPA 1,JARDIN,260.90,27394.50,27394.50,NaN,9920379.0,CASADO,1968-05-03,55.0,INDEPENDIENTE,Piura,Piura,Castilla,NaN,NaN,Asesor,Facebook,KENNY SMITH SANCARRANCO BAZAN,TAHITI BLUE - ETAPA 1,JARDIN,260.90,27394.50,15%,120.0,0.00,27394.50,FINANCIADO,51155.93,11510.10,22.50,NaN,970280027

In [109]:
reporteR['CU_CRUCE'] = reporteR['CLIENTE']+'-'+reporteR['LOTE']+'-'+reporteR['ESTADO VENTA']

In [110]:
cmr_leads_ventas_totales2['CU_CRUCE'] = cmr_leads_ventas_totales2['CLIENTE']+'-'+cmr_leads_ventas_totales2['LOTE']+'-'+cmr_leads_ventas_totales2['ESTADO VENTA']

In [111]:
prueba = pd.merge(cmr_leads_ventas_totales2,reporteR, how='left', on = 'CU_CRUCE')

In [112]:
prueba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1122 entries, 0 to 1121
Data columns (total 68 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA REGISTRO LEADS        882 non-null    datetime64[ns]
 1   CLIENTE_x                   1122 non-null   object
 2   DIRECCION                   882 non-null    object
 3   CANAL                       869 non-null    object
 4   ORIGEN                      1122 non-null   object
 5   VENDEDORES                  1120 non-null   object
 6   CELULAR CMR                 1122 non-null   object
 7   FECHA REGISTRO CMR          1122 non-null   datetime64[ns]
 8   HORA REGISTRO CMR           207 non-null    datetime64[ns]
 9   NIVEL DE INTERES            1122 non-null   object
 10  NOMBRE PROXIMO EVENTO       164 non-null    object
 11  FECHA PROXIMO EVENTO        164 non-null    object
 12  CELULAR                     882 non-null    object
 13  FECHA DE ULTIMA INTERACION  1117 non-null   datetime64[ns]
 14  FECHA VENTA_x               1122 non-null   datetime64[ns]
 15  HORA VENTA                  1122 non-null   datetime64[ns]
 16  DNI                         1122 non-null   int64
 17  VENDEDOR                    1122 non-null   object
 18  CODIGO                      1122 non-null   object
 19  LOTE_x                      1122 non-null   object
 20  ubicacion                   1122 non-null   object
 21  PRECIO_x                    1122 non-null   float64
 22  PrecioCliente               1122 non-null   float64
 23  N CUOTAS                    1122 non-null   int64
 24  ESTADO VENTA_x              1122 non-null   object
 25  FechaDeposito               1116 non-null   object
 26  contrato                    981 non-null    float64
 27  fecha_contrato              981 non-null    object
 28  formapago                   1122 non-null   object
 29  ORIGEN_SINCERADO            1122 non-null   object
 30  Proyecto                    1122 non-null   object
 31  UBICACION_LOTE              1122 non-null   object
 32  Area Lote                   1122 non-null   float64
 33  Precio                      1122 non-null   float64
 34  Precio F.                   1122 non-null   float64
 35  Valor Cuota                 88 non-null     float64
 36  CU_CRUCE                    1122 non-null   object
 37  CLIENTE_y                   1117 non-null   object
 38  DNI_R                       1117 non-null   float64
 39  ESTADO CIVIL                1117 non-null   object
 40  FECHA NACIMIENTO            1070 non-null   object
 41  EDAD                        1070 non-null   float64
 42  PROFESION                   600 non-null    object
 43  DEPARTAMENTO                1117 non-null   object
 44  PROVINCIA                   1117 non-null   object
 45  DISTRITO                    1117 non-null   object
 46  MOTIVO COMPRA               751 non-null    object
 47  CANAL_R                     877 non-null    object
 48  ORIGEN_R                    1117 non-null   object
 49  MEDIO DE CAPTACION          1117 non-null   object
 50  ASESOR                      1117 non-null   object
 51  ETAPA                       1117 non-null   object
 52  UBICACION                   1117 non-null   object
 53  LOTE_y                      1117 non-null   object
 54  AREA                        1117 non-null   float64
 55  PRECIO_y                    1117 non-null   float64
 56  TASA                        1117 non-null   object
 57  CUOTAS                      1117 non-null   float64
 58  DESCUENTO                   1117 non-null   float64
 59  PRECIO FINAL                1117 non-null   float64
 60  FINANCIAMIENTO              1117 non-null   object
 61  FECHA VENTA_y               1117 non-null   datetime64[ns]
 62  ESTADO VENTA_y              1117 non-null   object
 63  MONTO FINAL                 1117 non-null   float64
 64  TOTAL PAGANDO               1117 non-null   float64
 65  PORCENTAJE P                1117 non-null   float64
 66  CORREO                      1070 non-null   object
 67  CELULAR_R                   1117 non-null   object
dtypes: datetime64[ns](7), float64(17), int64(2), object(42)
memory usage: 604.8+ KB

In [113]:
data_global.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1122 entries, 0 to 1121
Data columns (total 63 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA REGISTRO LEADS        882 non-null    datetime64[ns]
 1   CLIENTE                     1122 non-null   object
 2   DIRECCION                   882 non-null    object
 3   CANAL                       869 non-null    object
 4   ORIGEN                      1122 non-null   object
 5   VENDEDORES                  1120 non-null   object
 6   CELULAR CMR                 1122 non-null   object
 7   FECHA REGISTRO CMR          1122 non-null   datetime64[ns]
 8   HORA REGISTRO CMR           207 non-null    datetime64[ns]
 9   NIVEL DE INTERES            1122 non-null   object
 10  NOMBRE PROXIMO EVENTO       164 non-null    object
 11  FECHA PROXIMO EVENTO        164 non-null    object
 12  CELULAR                     882 non-null    object
 13  FECHA DE ULTIMA INTERACION  1117 non-null   datetime64[ns]
 14  FECHA VENTA                 1122 non-null   datetime64[ns]
 15  HORA VENTA                  1122 non-null   datetime64[ns]
 16  DNI                         1122 non-null   int64
 17  VENDEDOR                    1122 non-null   object
 18  CODIGO                      1122 non-null   object
 19  LOTE                        1122 non-null   object
 20  ubicacion                   1122 non-null   object
 21  PRECIO_x                    1122 non-null   float64
 22  PrecioCliente               1122 non-null   float64
 23  N CUOTAS                    1122 non-null   int64
 24  ESTADO VENTA                1122 non-null   object
 25  FechaDeposito               1116 non-null   object
 26  contrato                    981 non-null    float64
 27  fecha_contrato              981 non-null    object
 28  formapago                   1122 non-null   object
 29  ORIGEN_SINCERADO            1122 non-null   object
 30  Proyecto                    1122 non-null   object
 31  UBICACION_LOTE              1122 non-null   object
 32  Area Lote                   1122 non-null   float64
 33  Precio                      1122 non-null   float64
 34  Precio F.                   1122 non-null   float64
 35  Valor Cuota                 88 non-null     float64
 36  DNI_R                       1117 non-null   float64
 37  ESTADO CIVIL                1117 non-null   object
 38  FECHA NACIMIENTO            1070 non-null   object
 39  EDAD                        1070 non-null   float64
 40  PROFESION                   600 non-null    object
 41  DEPARTAMENTO                1117 non-null   object
 42  PROVINCIA                   1117 non-null   object
 43  DISTRITO                    1117 non-null   object
 44  MOTIVO COMPRA               751 non-null    object
 45  CANAL_R                     877 non-null    object
 46  ORIGEN_R                    1117 non-null   object
 47  MEDIO DE CAPTACION          1117 non-null   object
 48  ASESOR                      1117 non-null   object
 49  ETAPA                       1117 non-null   object
 50  UBICACION                   1117 non-null   object
 51  AREA                        1117 non-null   float64
 52  PRECIO_y                    1117 non-null   float64
 53  TASA                        1117 non-null   object
 54  CUOTAS                      1117 non-null   float64
 55  DESCUENTO                   1117 non-null   float64
 56  PRECIO FINAL                1117 non-null   float64
 57  FINANCIAMIENTO              1117 non-null   object
 58  MONTO FINAL                 1117 non-null   float64
 59  TOTAL PAGANDO               1117 non-null   float64
 60  PORCENTAJE P                1117 non-null   float64
 61  CORREO                      1070 non-null   object
 62  CELULAR_R                   1117 non-null   object
dtypes: datetime64[ns](6), float64(17), int64(2), object(38)
memory usage: 561.0+ KB

In [114]:
data_global['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    762
VENCIDA           149
RESOLUCIÓN         77
DEVOLUCION C.I     48
DESISTIMIENTO      47
PRE-RESUELTO       32
SEPARACION          7
Name: ESTADO VENTA, dtype: int64

## PARA MKT

In [148]:
#data_global.to_excel('TAHITI_DATAGLOBAL_MKT.xlsx',index=False)

In [112]:
#reporte = pd.read_excel('Cruce_Info_Global.xlsx')

## COBRANZAN PARA POWER BI

### Cruzar Info con el Area Creditos  y Cobranzas

In [115]:
area_creditos =  pd.read_excel('Reporte Cobranzas/REPORTE CIERRE COBRANZA MARZO 2023.xlsx', sheet_name='TAHITI')

In [116]:
area_creditos.columns = area_creditos.columns.str.upper().str.strip()

In [117]:
area_creditos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   N°                    954 non-null    int64
 1   CÓDIGO DNI+LOTE       954 non-null    object
 2   ETAPA                 954 non-null    object
 3   LOTE                  954 non-null    object
 4   DNI                   954 non-null    int64
 5   CLIENTE               954 non-null    object
 6   MES VTA               954 non-null    object
 7   AÑO VTA               954 non-null    int64
 8   FECHA VENCIMIENTO     617 non-null    datetime64[ns]
 9   ASESOR                954 non-null    object
 10  VIGENTE               954 non-null    object
 11  AREA_LOTES            954 non-null    float64
 12  TIPO DE LOTE          954 non-null    object
 13  FORMAPAGO             954 non-null    object
 14  PRECIO                954 non-null    float64
 15  CUOTAS CANCELADAS     954 non-null    int64
 16  CUOTAS VENC           954 non-null    int64
 17  CUOTAS PEND           954 non-null    int64
 18  TOTAL DE CUOTAS       954 non-null    int64
 19  MORA X DIA            954 non-null    object
 20  ESTADO VENTA          954 non-null    object
 21  STATUS LOTE           954 non-null    object
 22  STATUS PAGO           616 non-null    object
 23  CUOTAS VENC.1         954 non-null    int64
 24  STATUS MORA           184 non-null    object
 25  STATUS TOTAL          954 non-null    object
 26  STATUS TOTAL FINAL    954 non-null    object
 27  STATUS TOTAL FINAL 1  954 non-null    object
 28  STATUS TOTAL FINAL 2  954 non-null    object
 29  CORREO                954 non-null    object
 30  TEL1                  954 non-null    object
 31  TEL2                  954 non-null    object
 32  DIR                   954 non-null    object
 33  DISTRITO              954 non-null    object
 34  PROVINCIA             954 non-null    object
 35  DEPARTAMENTO          954 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(8), object(25)
memory usage: 268.4+ KB

In [118]:
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.upper()
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.upper()
area_creditos['DEPARTAMENTO'] = area_creditos['DEPARTAMENTO'].str.upper()

In [119]:
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('MORROPÓN','MORROPON')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('PROV. CONST. DEL CALLAO','CALLAO')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('CONCEPCIÓN','CONCEPCION')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('VIRÚ','VIRU')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('CONTUMAZÁ','CONTUMAZA')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('CELENDÍN','CELENDIN')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('CAMANÁ','CAMANA')
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('LA CONVENCIÓN','LA CONVENCION')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\2547899569.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.replace('PROV. CONST. DEL CALLAO','CALLAO')

In [120]:
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.replace('BRENA','BREÑA')
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.replace('LOS BANOS DEL INCA','LOS BAÑOS DEL INCA')
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.replace('PARINAS','PARIÑAS')
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.replace('VEINTISEIS DE OCTUBRE','PIURA')
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.replace('PUEBLO LIBRE','CARABAYLLO')

In [121]:
area_creditos['PROVINCIA'] = area_creditos['PROVINCIA'].str.title()
area_creditos['DISTRITO'] = area_creditos['DISTRITO'].str.title()
area_creditos['DEPARTAMENTO'] = area_creditos['DEPARTAMENTO'].str.title()

In [122]:
area_creditos['DNI_'] = area_creditos['CÓDIGO DNI+LOTE'].str.split(";",expand=True,)[0]

In [123]:
con_coma = area_creditos[(area_creditos['CLIENTE'].str.contains(','))]

In [124]:
con_coma[['APELLIDO','NOMBRE']] = area_creditos.CLIENTE.str.split(",",expand=True,)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\3678684810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  con_coma[['APELLIDO','NOMBRE']] = area_creditos.CLIENTE.str.split(",",expand=True,)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\3678684810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  con_coma[['APELLIDO','NOMBRE']] = area_creditos.CLIENTE.str.split(",",expand=True,)

In [125]:
con_coma['APELLIDO'] = con_coma['APELLIDO'].str.strip().str.upper()
con_coma['NOMBRE'] = con_coma['NOMBRE'].str.strip().str.upper()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\1107912395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  con_coma['APELLIDO'] = con_coma['APELLIDO'].str.strip().str.upper()
C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\1107912395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  con_coma['NOMBRE'] = con_coma['NOMBRE'].str.strip().str.upper()

In [126]:
area_creditos_Nov = con_coma.drop(columns=['DNI','CLIENTE','FECHA VENCIMIENTO'])

In [127]:
area_creditos_Nov['CLIENTE'] = area_creditos_Nov['NOMBRE']+' ' + area_creditos_Nov['APELLIDO']
area_creditos_Nov['CLIENTE'] = area_creditos_Nov['CLIENTE'].str.replace('  ',' ')

In [128]:
area_creditos_Nov2 = area_creditos_Nov.drop(columns=['NOMBRE','APELLIDO'])

In [129]:
sin_coma = area_creditos[~(area_creditos['CLIENTE'].str.contains(','))]

In [130]:
sin_coma2 = sin_coma.drop(columns=['DNI','FECHA VENCIMIENTO'])

In [131]:
area_creditos_Nov3 = pd.concat([area_creditos_Nov2,sin_coma2])

In [132]:
area_creditos_Nov3

,N°,CÓDIGO DNI+LOTE,ETAPA,LOTE,MES VTA,AÑO VTA,ASESOR,VIGENTE,AREA_LOTES,TIPO DE LOTE,FORMAPAGO,PRECIO,CUOTAS CANCELADAS,CUOTAS VENC,CUOTAS PEND,TOTAL DE CUOTAS,MORA X DIA,ESTADO VENTA,STATUS LOTE,STATUS PAGO,CUOTAS VENC.1,STATUS MORA,STATUS TOTAL,STATUS TOTAL FINAL,STATUS TOTAL FINAL 1,STATUS TOTAL FINAL 2,CORREO,TEL1,TEL2,DIR,DISTRITO,PROVINCIA,DEPARTAMENTO,DNI_,CLIENTE
0,1,001125876;EE16,TAHITI BLUE - ETAPA 1,EE16,Febrero,2021,ANDRES,INACTIVO,270.30,JARDIN,FINANCIADO,28381.48,24,2,94,120,31-60,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,2,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,GMASCARENOM@GMAIL.COM,(en blanco),960851410,AVENIDA CHIRICHIGNO MZ. C LT. 16 SAN EDUARDO,Piura,Piura,Piura,001125876,GUILLERMO ANDRES MASCAREÑO MEZZANO
1,2,001268116;EE10,TAHITI BLUE - ETAPA 1,EE10,Marzo,2021,RUBEN,ACTIVO,282.60,JARDIN,CONTADO,27173.00,1,0,0,1,0,PAGANDO CUOTAS,LIQUIDADO,NaN,0,NaN,LIQUIDADO,LIQUIDADO,LIQUIDADO,EN PROCESO DE PAGO,LFRACICA@GMAIL.COM,965468715,977933409,MZ. D LOTE 06-02 URB. QUINTA ANA MARIA,Piura,Piura,Piura,001268116,LIZANDRO FABIAN FRACICA GUTIERREZ
2,3,001275610;DC02,TAHITI BLUE - ETAPA 2,DC02,Octubre,2022,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,JEISON.MOR@HOTMAIL.ES,(en blanco),965445227,MZ C LT 7 JR LOS PICAFLORES,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO
3,4,001275610;DC04,TAHITI BLUE - ETAPA 2,DC04,Octubre,2022,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,JEISON.MOR@HOTMAIL.ES,(en blanco),965445227,MZ C LT 7 JR LOS PICAFLORES,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO
4,5,001275610;DC05,TAHITI BLUE - ETAPA 2,DC05,Octubre,2022,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,JEISON.MOR@HOTMAIL.ES,(en blanco),965445227,MZ C LT 7 JR LOS PICAFLORES,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,287,20605175831;BE02,TAHITI BLUE - ETAPA 8,BE02,Febrero,2023,FRANCESCA,ACTIVO,372.58,FRENTE A PARQUE,FINANCIADO,72222.36,1,0,71,72,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,MGANOZAY@WIGANCORP.COM.PE,(en blanco),947633084,JR H MZ 241 LOTE 1 ZONA INDUSTRIAL,Piura,Piura,Piura,20605175831,WIGAN CORPORACION SOCIEDAD ANONIMA CERRADA
287,288,20605536230;EG14,TAHITI BLUE - ETAPA 1,EG14,Marzo,2021,MILAGROS DEL PILAR,INACTIVO,269.50,JARDIN,FINANCIADO,28297.48,1,0,118,119,0,RESOLUCIÓN,RESUELTO,NaN,0,NaN,RESUELTO,CAIDOS,RESUELTO,CAIDOS,JUOS2106@GMAIL.COM,(en blanco),998271628,Ca Arequipa 642 Int.44 Cent. Piura (PLAZA FUERTE 6° PISO OFICINA 01),Piura,Piura,Piura,20605536230,HP&PROJECT INGENIERIA SERVICIOS GENERALES E.I.R.L.
288,289,20605717978;EF07,TAHITI BLUE - ETAPA 1,EF07,Octubre,2022,FRANCISCO JAVIER,INACTIVO,255.90,JARDIN,FINANCIADO,46369.55,5,1,66,72,0-30,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,1,NORMAL,NORMAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,YHERSON221187@GMAIL.COM,(en blanco),931033948,AV. DEL EJERCITO 740 - URB. SANTA CRUZ - MIRAFLORES - LIMA - LIMA,Callao,Callao,Callao,20605717978,SERVICIOS MéDICOS Y NEGOCIACIONES JMA SAC
289,290,20607301906;EQ24,TAHITI BLUE - ETAPA 1,EQ24,Octubre,2021,FRANCISCO JAVIER,INACTIVO,250.00,FRENTE A CALLE,FINANCIADO,29999.96,1,0,119,120,0,RESOLUCIÓN,RESUELTO,NaN,0,NaN,RESUELTO,CAIDOS,RESUELTO,CAIDOS,CARMEN.MADRIDVILLARREYES@GMAIL.COM,(en blanco),965482609,CALLE J M REYGADA 325 INT 01 ASENT H EL OBRERO SULLANA - SULLANA - PIURA,Sullana,Sullana,Piura,20607301906,AGROMETAL DEL PERU SOCIEDAD ANONIMA CERRADA
290,291,20608821890;DB20,TAHITI BLUE - ETAPA 2,DB20,Octubre,2022,LUIS GERARDO,ACTIVO,250.00,FRENTE A CALLE,FINANCIADO,42139.99,5,0,69,74,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,ESTUDIOCONTADORESVQ@GMAIL.COM,(en blanco),938827161,JR. MAIPU 116 URB. MARANGA ET. UNO - SAN MIGUEL - LIMA - LIMA,San Miguel,Lima,Lima,20608821890,J&P INMOBILIARIA Y NEGOCIOS S.A.C.

In [133]:
area_creditos_Nov3['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS    754
PRE RESUELTO       67
DESISTIMIENTO      45
RESOLUCIÓN         44
DEVOLUCION         44
Name: ESTADO VENTA, dtype: int64

In [134]:
cmr_leads_ventas_totales['FECHA VENTA'].max()

Timestamp('2023-04-01 00:00:00')

In [135]:
cmr_leads_ventas_totales['ESTADO VENTA'].value_counts()

PAGANDO CUOTAS          763
VENCIDA                 147
PRE-RESUELTO             59
DEVOLUCION C.I           44
DESISTIMIENTO            44
RESOLUCIÓN               44
SEPARACION                3
VALIDAR SEPARACIÓN\t      1
Name: ESTADO VENTA, dtype: int64

In [136]:
cmr_leads_ventas_totales['CLIENTE']  = cmr_leads_ventas_totales['CLIENTE'].str.replace('ENMA ROSA DE LOS MILAGROS PIEDRA MAZA',
                                                                                       'EMMA ROSA DE LOS MILAGROS PIEDRA MAZA')

In [137]:
cliente_dict = {
    '"M&Ñ" SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA':'VANESSA MARIAELENA TORIBIO TROYA',
    '2R SEGURIDAD Y SISTEMAS CONTRA INCENDIOS E.I.R.L':'DIEGO ALONSO REYNA ZUÑIGA',
    'AGROMETAL DEL PERU SOCIEDAD ANONIMA CERRADA':'CARMEN YOLANDA MADRID VILLAREYES',
    'ANGULO BERNAL JOSE CARLOS':'JOSE CARLOS ANGULO BERNAL',
    'AZIZE INGENIEROS S.A.C.':'CESAR ALBERTO ORTIZ PAMPAS',
    'C & N ASOCIADOS S.R.L':'CYNTHIA VANESSA ESTRADA SOSAYA',
    'CENTRO OFTALMOLOGICO KRISTELL E.I.R.L.':'KARINA LISSET ROJAS VALDIVIA',
    'CONSTRUCCIONES Y SERVICIOS GENERALES SAN MARTIN DE TOURS SOCIEDAD ANONIMA CERRADA':'JULIA ALDANA JACINTO',
    'HP&PROJECT INGENIERIA SERVICIOS GENERALES E.I.R.L.':'JUNIOR OSMAR HERNAN PINTADO GARRIDO',
    'J&P INMOBILIARIA Y NEGOCIOS S.A.C.':'VICTOR JOEL VELARDE QUEVEDO',
    'J.V.P INGENIEROS CONSTRUCTORES S.R.L':'VICTOR CHUQUILLANQUI CHINGUEL',
    'NEFROCONSULT EIRL':'JORGE DAVID SALOME LUNA',
    'R.E.E. CONTRATISTAS GENERALES & INVERSIONES S.A.C.':'OMAR LUIS CASTAÑEDA ECHEVARRIA',
    'REYES ARAUJO MOISES DAVID':'TATIANA MARIELLA VILLACRIZ CASTILLO',
    'SERVICIOS MéDICOS Y NEGOCIACIONES JMA SAC':'YHERSON JHAMES MENDOZA ABANTO',
    'M&Ñ SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA':'VANESSA MARIAELENA TORIBIO TROYA',
    'WIGAN CORPORACION SOCIEDAD ANONIMA CERRADA':'JONATHAN MARTIN LUDEÑA PANTA'
}

In [138]:
area_creditos_Nov4 = area_creditos_Nov3.replace({'CLIENTE':cliente_dict})

In [150]:
cmr_leads_ventas_totales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1105 entries, 0 to 1104
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FECHA REGISTRO LEADS        866 non-null    datetime64[ns]
 1   CLIENTE                     1105 non-null   object
 2   DIRECCION                   866 non-null    object
 3   CANAL                       858 non-null    object
 4   ORIGEN                      1105 non-null   object
 5   VENDEDORES                  1103 non-null   object
 6   CELULAR CMR                 1105 non-null   object
 7   FECHA REGISTRO CMR          1105 non-null   datetime64[ns]
 8   HORA REGISTRO CMR           194 non-null    datetime64[ns]
 9   NIVEL DE INTERES            1105 non-null   object
 10  NOMBRE PROXIMO EVENTO       155 non-null    object
 11  FECHA PROXIMO EVENTO        155 non-null    object
 12  CELULAR                     866 non-null    object
 13  FECHA DE ULTIMA INTERACION  1100 non-null   datetime64[ns]
 14  FECHA VENTA                 1105 non-null   datetime64[ns]
 15  HORA VENTA                  1105 non-null   datetime64[ns]
 16  DNI                         1105 non-null   int64
 17  VENDEDOR                    1105 non-null   object
 18  CODIGO                      1105 non-null   object
 19  LOTE                        1105 non-null   object
 20  ubicacion                   1105 non-null   object
 21  PRECIO                      1105 non-null   float64
 22  PrecioCliente               1105 non-null   float64
 23  N CUOTAS                    1105 non-null   int64
 24  ESTADO VENTA                1105 non-null   object
 25  FechaDeposito               1098 non-null   object
 26  contrato                    968 non-null    float64
 27  fecha_contrato              968 non-null    object
 28  formapago                   1105 non-null   object
 29  ORIGEN_SINCERADO            1105 non-null   object
dtypes: datetime64[ns](6), float64(3), int64(2), object(19)
memory usage: 267.6+ KB

In [151]:
ventas_sinceradas = cmr_leads_ventas_totales.iloc[:,[14,15,1,16,17,18,19,20,21,22,23,24]] # se revisan siempre

In [152]:
ventas_sinceradas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1105 entries, 0 to 1104
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FECHA VENTA    1105 non-null   datetime64[ns]
 1   HORA VENTA     1105 non-null   datetime64[ns]
 2   CLIENTE        1105 non-null   object
 3   DNI            1105 non-null   int64
 4   VENDEDOR       1105 non-null   object
 5   CODIGO         1105 non-null   object
 6   LOTE           1105 non-null   object
 7   ubicacion      1105 non-null   object
 8   PRECIO         1105 non-null   float64
 9   PrecioCliente  1105 non-null   float64
 10  N CUOTAS       1105 non-null   int64
 11  ESTADO VENTA   1105 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 112.2+ KB

In [153]:
cliente_creditos = area_creditos_Nov4['CLIENTE'].unique().tolist()

In [154]:
cliente_ventas_since = ventas_sinceradas['CLIENTE'].unique().tolist()

In [155]:
diff_= set(cliente_creditos)-set(cliente_ventas_since)
diff_
#DN10 IVAN
#

set()

In [156]:
#ventas_sinceradas[ventas_sinceradas['CLIENTE'] == 'JONATHAN MARTIN LUDEÑA PANTA']

In [157]:
#area_creditos_Nov4[area_creditos_Nov4['CLIENTE'] == 'WIGAN CORPORACION SOCIEDAD ANONIMA CERRADA']

In [160]:
ventas_pagando_cuotas = ventas_sinceradas[(ventas_sinceradas['ESTADO VENTA']=='PAGANDO CUOTAS')&\
                                         (ventas_sinceradas['FECHA VENTA']<='2023-03-31')]

In [161]:
ventas_pagando_cuotas.shape[0]

763

In [162]:
len(ventas_pagando_cuotas['CLIENTE'].unique().tolist())

648

In [169]:
len(creditos_pagando_cuotas['CLIENTE'].unique().tolist())

641

In [163]:
creditos_pagando_cuotas = area_creditos_Nov4[area_creditos_Nov4['ESTADO VENTA']=='PAGANDO CUOTAS']

In [164]:
creditos_pagando_cuotas.shape[0]

754

In [165]:
cliente_Ventas_pc = ventas_pagando_cuotas['CLIENTE'].unique().tolist()
cliente_Creditos_pc = creditos_pagando_cuotas['CLIENTE'].unique().tolist()

In [166]:
diferente = set(cliente_Creditos_pc)-set(cliente_Ventas_pc)  ## CLIENTES QUE NO FIGURAN EN PAGANDO CUOTAS
diferente                                                    #porque cambio su estado de venta

set()

In [167]:
diferente2 = set(cliente_Ventas_pc)-set(cliente_Creditos_pc) ## CLIENTE QUE NO FIGURA EN VENTAS DE COBRANZAS
diferente2                                                  # porque el excel de cobranas esta desactualizado

{'DAVID EDUARDO REQUENA CORTEZ',
 'DIEGO ALONSO REYNA ZUÑIGA',
 'GEANCARLOS ALONSO CASTRO CHUNA',
 'JIMMY AGUSTO PARDO LAMA',
 'JOSE LUIS GONZALES QUEVEDO',
 'MARIA EUGENIA CHERRES CANO',
 'VERONICA CECILIA CASTILLO CHUMACERO'}

In [170]:
lote_Ventas_pc = ventas_pagando_cuotas['LOTE'].unique().tolist()
lote_Creditos_pc = creditos_pagando_cuotas['LOTE'].unique().tolist()

In [171]:
diferentelote = set(lote_Creditos_pc)-set(lote_Ventas_pc)  ## LOTES QUE NO FIGURAN EN PAGANDO CUOTAS
diferentelote

set()

In [172]:
diferente2lote = set(lote_Ventas_pc)-set(lote_Creditos_pc) ## LOTES QUE NO FIGURA EN VENTAS DE COBRANZAS
diferente2lote

{'DE09', 'DE17', 'DH21', 'DJ04', 'DJ06', 'DQ21', 'DÑ01', 'EA04', 'EO15'}

In [173]:
creditos_pagando_cuotas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 754 entries, 0 to 290
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   N°                    754 non-null    int64
 1   CÓDIGO DNI+LOTE       754 non-null    object
 2   ETAPA                 754 non-null    object
 3   LOTE                  754 non-null    object
 4   MES VTA               754 non-null    object
 5   AÑO VTA               754 non-null    int64
 6   ASESOR                754 non-null    object
 7   VIGENTE               754 non-null    object
 8   AREA_LOTES            754 non-null    float64
 9   TIPO DE LOTE          754 non-null    object
 10  FORMAPAGO             754 non-null    object
 11  PRECIO                754 non-null    float64
 12  CUOTAS CANCELADAS     754 non-null    int64
 13  CUOTAS VENC           754 non-null    int64
 14  CUOTAS PEND           754 non-null    int64
 15  TOTAL DE CUOTAS       754 non-null    int64
 16  MORA X DIA            754 non-null    object
 17  ESTADO VENTA          754 non-null    object
 18  STATUS LOTE           754 non-null    object
 19  STATUS PAGO           616 non-null    object
 20  CUOTAS VENC.1         754 non-null    int64
 21  STATUS MORA           184 non-null    object
 22  STATUS TOTAL          754 non-null    object
 23  STATUS TOTAL FINAL    754 non-null    object
 24  STATUS TOTAL FINAL 1  754 non-null    object
 25  STATUS TOTAL FINAL 2  754 non-null    object
 26  CORREO                754 non-null    object
 27  TEL1                  754 non-null    object
 28  TEL2                  754 non-null    object
 29  DIR                   754 non-null    object
 30  DISTRITO              754 non-null    object
 31  PROVINCIA             754 non-null    object
 32  DEPARTAMENTO          754 non-null    object
 33  DNI_                  754 non-null    object
 34  CLIENTE               754 non-null    object
dtypes: float64(2), int64(7), object(26)
memory usage: 212.1+ KB

In [174]:
creditos_pagando_cuotas['Codigo_Cruce'] = creditos_pagando_cuotas['CLIENTE']+'-'+creditos_pagando_cuotas['LOTE']+'-'+creditos_pagando_cuotas['ESTADO VENTA']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16716\3330567532.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  creditos_pagando_cuotas['Codigo_Cruce'] = creditos_pagando_cuotas['CLIENTE']+'-'+creditos_pagando_cuotas['LOTE']+'-'+creditos_pagando_cuotas['ESTADO VENTA']

In [175]:
data_final_cobranzas = creditos_pagando_cuotas.drop(columns=['N°','MES VTA','AÑO VTA','CORREO','TEL1','TEL2','DIR'])

In [176]:
data_final_cobranzas

,CÓDIGO DNI+LOTE,ETAPA,LOTE,ASESOR,VIGENTE,AREA_LOTES,TIPO DE LOTE,FORMAPAGO,PRECIO,CUOTAS CANCELADAS,CUOTAS VENC,CUOTAS PEND,TOTAL DE CUOTAS,MORA X DIA,ESTADO VENTA,STATUS LOTE,STATUS PAGO,CUOTAS VENC.1,STATUS MORA,STATUS TOTAL,STATUS TOTAL FINAL,STATUS TOTAL FINAL 1,STATUS TOTAL FINAL 2,DISTRITO,PROVINCIA,DEPARTAMENTO,DNI_,CLIENTE,Codigo_Cruce
0,001125876;EE16,TAHITI BLUE - ETAPA 1,EE16,ANDRES,INACTIVO,270.30,JARDIN,FINANCIADO,28381.48,24,2,94,120,31-60,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,2,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Piura,Piura,Piura,001125876,GUILLERMO ANDRES MASCAREÑO MEZZANO,GUILLERMO ANDRES MASCAREÑO MEZZANO-EE16-PAGANDO CUOTAS
1,001268116;EE10,TAHITI BLUE - ETAPA 1,EE10,RUBEN,ACTIVO,282.60,JARDIN,CONTADO,27173.00,1,0,0,1,0,PAGANDO CUOTAS,LIQUIDADO,NaN,0,NaN,LIQUIDADO,LIQUIDADO,LIQUIDADO,EN PROCESO DE PAGO,Piura,Piura,Piura,001268116,LIZANDRO FABIAN FRACICA GUTIERREZ,LIZANDRO FABIAN FRACICA GUTIERREZ-EE10-PAGANDO CUOTAS
2,001275610;DC02,TAHITI BLUE - ETAPA 2,DC02,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO,JERSSON DAVID MORA SARMIENTO-DC02-PAGANDO CUOTAS
3,001275610;DC04,TAHITI BLUE - ETAPA 2,DC04,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO,JERSSON DAVID MORA SARMIENTO-DC04-PAGANDO CUOTAS
4,001275610;DC05,TAHITI BLUE - ETAPA 2,DC05,RAMIRO CIRO ERNESTO,ACTIVO,250.00,FRENTE A PARQUE,FINANCIADO,48460.97,1,3,154,158,61-90,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Caraz,Huaylas,Ancash,001275610,JERSSON DAVID MORA SARMIENTO,JERSSON DAVID MORA SARMIENTO-DC05-PAGANDO CUOTAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,20601975191;DM08,TAHITI BLUE - ETAPA 2,DM08,FRANCISCO JAVIER,INACTIVO,210.00,JARDIN,FINANCIADO,31458.01,16,0,104,120,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Piura,Piura,Piura,20601975191,JORGE DAVID SALOME LUNA,JORGE DAVID SALOME LUNA-DM08-PAGANDO CUOTAS
284,20603050674;EQ44,TAHITI BLUE - ETAPA 1,EQ44,ANA MARIA,INACTIVO,205.06,FRENTE A CALLE,FINANCIADO,33219.71,15,0,137,152,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Castilla,Piura,Piura,20603050674,KARINA LISSET ROJAS VALDIVIA,KARINA LISSET ROJAS VALDIVIA-EQ44-PAGANDO CUOTAS
286,20605175831;BE02,TAHITI BLUE - ETAPA 8,BE02,FRANCESCA,ACTIVO,372.58,FRENTE A PARQUE,FINANCIADO,72222.36,1,0,71,72,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Piura,Piura,Piura,20605175831,JONATHAN MARTIN LUDEÑA PANTA,JONATHAN MARTIN LUDEÑA PANTA-BE02-PAGANDO CUOTAS
288,20605717978;EF07,TAHITI BLUE - ETAPA 1,EF07,FRANCISCO JAVIER,INACTIVO,255.90,JARDIN,FINANCIADO,46369.55,5,1,66,72,0-30,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,1,NORMAL,NORMAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,Callao,Callao,Callao,20605717978,YHERSON JHAMES MENDOZA ABANTO,YHERSON JHAMES MENDOZA ABANTO-EF07-PAGANDO CUOTAS
290,20608821890;DB20,TAHITI BLUE - ETAPA 2,DB20,LUIS GERARDO,ACTIVO,250.00,FRENTE A CALLE,FINANCIADO,42139.99,5,0,69,74,0,PAGANDO CUOTAS,EN PROCESO DE PAGO,PUNTUAL,0,NaN,PUNTUAL,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,San Miguel,Lima,Lima,20608821890,VICTOR JOEL VELARDE QUEVEDO,VICTOR JOEL VELARDE QUEVEDO-DB20-PAGANDO CUOTAS

## COBRANZA PARA POWER BI

In [161]:
#data_final_cobranzas.to_excel('Cobranzas.xlsx', index = False)

In [162]:
data_final_cobranzas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 751 entries, 0 to 281
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CÓDIGO DNI+LOTE       751 non-null    object
 1   ETAPA                 751 non-null    object
 2   LOTE                  751 non-null    object
 3   ASESOR                751 non-null    object
 4   VIGENTE               751 non-null    object
 5   AREA_LOTES            751 non-null    float64
 6   TIPO DE LOTE          751 non-null    object
 7   FORMAPAGO             751 non-null    object
 8   PRECIO                751 non-null    float64
 9   CUOTAS CANCELADAS     751 non-null    int64
 10  CUOTAS VENC           751 non-null    int64
 11  CUOTAS PEND           751 non-null    int64
 12  TOTAL DE CUOTAS       751 non-null    int64
 13  MORA X DIA            751 non-null    object
 14  ESTADO VENTA          751 non-null    object
 15  STATUS LOTE           751 non-null    object
 16  STATUS PAGO           615 non-null    object
 17  CUOTAS VENC.1         751 non-null    int64
 18  STATUS MORA           183 non-null    object
 19  STATUS TOTAL          751 non-null    object
 20  STATUS TOTAL FINAL    751 non-null    object
 21  STATUS TOTAL FINAL 1  751 non-null    object
 22  STATUS TOTAL FINAL 2  751 non-null    object
 23  DISTRITO              751 non-null    object
 24  PROVINCIA             751 non-null    object
 25  DEPARTAMENTO          751 non-null    object
 26  DNI_                  751 non-null    object
 27  CLIENTE               751 non-null    object
 28  Codigo_Cruce          751 non-null    object
dtypes: float64(2), int64(5), object(22)
memory usage: 192.2+ KB

## COMPROBAR CONEXIONES

In [164]:
ventas_pagando_cuotas['Codigo_Cruce'] = ventas_pagando_cuotas['CLIENTE']+'-'+ventas_pagando_cuotas['LOTE']+'-'+ventas_pagando_cuotas['ESTADO VENTA']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12320\4279087450.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas_pagando_cuotas['Codigo_Cruce'] = ventas_pagando_cuotas['CLIENTE']+'-'+ventas_pagando_cuotas['LOTE']+'-'+ventas_pagando_cuotas['ESTADO VENTA']

In [169]:
creditos_pagando_cuotas[creditos_pagando_cuotas['CLIENTE'].str.contains('ROSA DE LOS MILAGROS')]

,N°,CÓDIGO DNI+LOTE,ETAPA,LOTE,MES VTA,AÑO VTA,ASESOR,VIGENTE,AREA_LOTES,TIPO DE LOTE,FORMAPAGO,PRECIO,CUOTAS CANCELADAS,CUOTAS VENC,CUOTAS PEND,TOTAL DE CUOTAS,MORA X DIA,ESTADO VENTA,STATUS LOTE,STATUS PAGO,CUOTAS VENC.1,STATUS MORA,STATUS TOTAL,STATUS TOTAL FINAL,STATUS TOTAL FINAL 1,STATUS TOTAL FINAL 2,CORREO,TEL1,TEL2,DIR,DISTRITO,PROVINCIA,DEPARTAMENTO,DNI_,CLIENTE,Codigo_Cruce
164,165,03878234;EQ28,TAHITI BLUE - ETAPA 1,EQ28,Noviembre,2021,LUIS FERNANDO,ACTIVO,250.0,FRENTE A CALLE,FINANCIADO,29999.96,12,3,105,120,31-60,PAGANDO CUOTAS,EN PROCESO DE PAGO,MOROSO,3,MODERADA,MODERADA,EN PROCESO DE PAGO,EN PROCESO DE PAGO,EN PROCESO DE PAGO,GUISSELLAPIEDRA@GMAIL.COM,(en blanco),941878950,CONJ. HAB . IGNACIO MERINO MZ N LOTE 5,Piura,Piura,Piura,03878234,EMMA ROSA DE LOS MILAGROS PIEDRA MAZA,EMMA ROSA DE LOS MILAGROS PIEDRA MAZA-EQ28-PAGANDO CUOTAS

In [170]:
ventas_pagando_cuotas[ventas_pagando_cuotas['CLIENTE'].str.contains('ROSA DE LOS MILAGROS')]

,FECHA VENTA,HORA VENTA,CLIENTE,DNI,VENDEDOR,CODIGO,LOTE,PRECIO,N CUOTAS,ESTADO VENTA,ORIGEN_SINCERADO,Codigo_Cruce
542,2021-11-18,2023-03-14 15:37:21,EMMA ROSA DE LOS MILAGROS PIEDRA MAZA,3878234,LUIS FERNANDO DELGADO WONG,VN0000831,EQ28,30000.0,120,PAGANDO CUOTAS,Asesor,EMMA ROSA DE LOS MILAGROS PIEDRA MAZA-EQ28-PAGANDO CUOTAS

In [165]:
df_cruce_webYcobranzas = pd.merge(creditos_pagando_cuotas,ventas_pagando_cuotas,on=['Codigo_Cruce'], how = 'right',
                                 suffixes=('_COBRANZAS', '_WEB'))

In [168]:
df_cruce_webYcobranzas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 751 entries, 0 to 750
Data columns (total 47 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   N°                      751 non-null    int64
 1   CÓDIGO DNI+LOTE         751 non-null    object
 2   ETAPA                   751 non-null    object
 3   LOTE_COBRANZAS          751 non-null    object
 4   MES VTA                 751 non-null    object
 5   AÑO VTA                 751 non-null    int64
 6   ASESOR                  751 non-null    object
 7   VIGENTE                 751 non-null    object
 8   AREA_LOTES              751 non-null    float64
 9   TIPO DE LOTE            751 non-null    object
 10  FORMAPAGO               751 non-null    object
 11  PRECIO_COBRANZAS        751 non-null    float64
 12  CUOTAS CANCELADAS       751 non-null    int64
 13  CUOTAS VENC             751 non-null    int64
 14  CUOTAS PEND             751 non-null    int64
 15  TOTAL DE CUOTAS         751 non-null    int64
 16  MORA X DIA              751 non-null    object
 17  ESTADO VENTA_COBRANZAS  751 non-null    object
 18  STATUS LOTE             751 non-null    object
 19  STATUS PAGO             615 non-null    object
 20  CUOTAS VENC.1           751 non-null    int64
 21  STATUS MORA             183 non-null    object
 22  STATUS TOTAL            751 non-null    object
 23  STATUS TOTAL FINAL      751 non-null    object
 24  STATUS TOTAL FINAL 1    751 non-null    object
 25  STATUS TOTAL FINAL 2    751 non-null    object
 26  CORREO                  751 non-null    object
 27  TEL1                    751 non-null    object
 28  TEL2                    751 non-null    object
 29  DIR                     751 non-null    object
 30  DISTRITO                751 non-null    object
 31  PROVINCIA               751 non-null    object
 32  DEPARTAMENTO            751 non-null    object
 33  DNI_                    751 non-null    object
 34  CLIENTE_COBRANZAS       751 non-null    object
 35  Codigo_Cruce            751 non-null    object
 36  FECHA VENTA             751 non-null    datetime64[ns]
 37  HORA VENTA              751 non-null    datetime64[ns]
 38  CLIENTE_WEB             751 non-null    object
 39  DNI                     751 non-null    int64
 40  VENDEDOR                751 non-null    object
 41  CODIGO                  751 non-null    object
 42  LOTE_WEB                751 non-null    object
 43  PRECIO_WEB              751 non-null    float64
 44  N CUOTAS                751 non-null    int64
 45  ESTADO VENTA_WEB        751 non-null    object
 46  ORIGEN_SINCERADO        751 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(9), object(33)
memory usage: 281.6+ KB

## CRUCE ENTRE PAGAN CUOTAS DE EXCEL DE LA WEB Y LA DATA DE COBRANZAS

In [181]:
df_cruce_webYcobranzas = pd.merge(creditos_pagando_cuotas,ventas_pagando_cuotas,on=['CLIENTE','LOTE'], how = 'right',
                                 suffixes=('_COBRANZAS', '_WEB'))

In [182]:
df_cruce_webYcobranzas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 751 entries, 0 to 750
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   N°                      751 non-null    int64
 1   CÓDIGO DNI+LOTE         751 non-null    object
 2   ETAPA                   751 non-null    object
 3   LOTE                    751 non-null    object
 4   MES VTA                 751 non-null    object
 5   AÑO VTA                 751 non-null    int64
 6   ASESOR                  751 non-null    object
 7   VIGENTE                 751 non-null    object
 8   AREA_LOTES              751 non-null    float64
 9   TIPO DE LOTE            751 non-null    object
 10  FORMAPAGO               751 non-null    object
 11  PRECIO_COBRANZAS        751 non-null    float64
 12  CUOTAS CANCELADAS       751 non-null    int64
 13  CUOTAS VENC             751 non-null    int64
 14  CUOTAS PEND             751 non-null    int64
 15  TOTAL DE CUOTAS         751 non-null    int64
 16  MORA X DIA              751 non-null    object
 17  ESTADO VENTA_COBRANZAS  751 non-null    object
 18  STATUS LOTE             751 non-null    object
 19  STATUS PAGO             615 non-null    object
 20  CUOTAS VENC.1           751 non-null    int64
 21  STATUS MORA             183 non-null    object
 22  STATUS TOTAL            751 non-null    object
 23  STATUS TOTAL FINAL      751 non-null    object
 24  STATUS TOTAL FINAL 1    751 non-null    object
 25  STATUS TOTAL FINAL 2    751 non-null    object
 26  CORREO                  751 non-null    object
 27  TEL1                    751 non-null    object
 28  TEL2                    751 non-null    object
 29  DIR                     751 non-null    object
 30  DISTRITO                751 non-null    object
 31  PROVINCIA               751 non-null    object
 32  DEPARTAMENTO            751 non-null    object
 33  DNI_                    751 non-null    object
 34  CLIENTE                 751 non-null    object
 35  FECHA VENTA             751 non-null    datetime64[ns]
 36  HORA VENTA              751 non-null    datetime64[ns]
 37  DNI                     751 non-null    int64
 38  VENDEDOR                751 non-null    object
 39  CODIGO                  751 non-null    object
 40  PRECIO_WEB              751 non-null    float64
 41  N CUOTAS                751 non-null    int64
 42  ESTADO VENTA_WEB        751 non-null    object
 43  ORIGEN_SINCERADO        751 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(9), object(30)
memory usage: 264.0+ KB

In [183]:
df_cruce_webYcobranzas[df_cruce_webYcobranzas['CÓDIGO DNI+LOTE'].isnull()]

Empty DataFrame
Columns: [N°, CÓDIGO DNI+LOTE, ETAPA, LOTE, MES VTA, AÑO VTA, ASESOR, VIGENTE, AREA_LOTES, TIPO DE LOTE, FORMAPAGO, PRECIO_COBRANZAS, CUOTAS CANCELADAS, CUOTAS VENC, CUOTAS PEND, TOTAL DE CUOTAS, MORA X DIA, ESTADO VENTA_COBRANZAS, STATUS LOTE, STATUS PAGO, CUOTAS VENC.1, STATUS MORA, STATUS TOTAL, STATUS TOTAL FINAL, STATUS TOTAL FINAL 1, STATUS TOTAL FINAL 2, CORREO, TEL1, TEL2, DIR, DISTRITO, PROVINCIA, DEPARTAMENTO, DNI_, CLIENTE, FECHA VENTA, HORA VENTA, DNI, VENDEDOR, CODIGO, PRECIO_WEB, N CUOTAS, ESTADO VENTA_WEB, ORIGEN_SINCERADO]
Index: []

In [184]:
df_cruce_webYcobranzas2 = pd.merge(creditos_pagando_cuotas,ventas_pagando_cuotas,on=['CLIENTE','LOTE'], how = 'left',
                                 suffixes=('_COBRANZAS', '_WEB'))

In [185]:
df_cruce_webYcobranzas2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 751 entries, 0 to 750
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   N°                      751 non-null    int64
 1   CÓDIGO DNI+LOTE         751 non-null    object
 2   ETAPA                   751 non-null    object
 3   LOTE                    751 non-null    object
 4   MES VTA                 751 non-null    object
 5   AÑO VTA                 751 non-null    int64
 6   ASESOR                  751 non-null    object
 7   VIGENTE                 751 non-null    object
 8   AREA_LOTES              751 non-null    float64
 9   TIPO DE LOTE            751 non-null    object
 10  FORMAPAGO               751 non-null    object
 11  PRECIO_COBRANZAS        751 non-null    float64
 12  CUOTAS CANCELADAS       751 non-null    int64
 13  CUOTAS VENC             751 non-null    int64
 14  CUOTAS PEND             751 non-null    int64
 15  TOTAL DE CUOTAS         751 non-null    int64
 16  MORA X DIA              751 non-null    object
 17  ESTADO VENTA_COBRANZAS  751 non-null    object
 18  STATUS LOTE             751 non-null    object
 19  STATUS PAGO             615 non-null    object
 20  CUOTAS VENC.1           751 non-null    int64
 21  STATUS MORA             183 non-null    object
 22  STATUS TOTAL            751 non-null    object
 23  STATUS TOTAL FINAL      751 non-null    object
 24  STATUS TOTAL FINAL 1    751 non-null    object
 25  STATUS TOTAL FINAL 2    751 non-null    object
 26  CORREO                  751 non-null    object
 27  TEL1                    751 non-null    object
 28  TEL2                    751 non-null    object
 29  DIR                     751 non-null    object
 30  DISTRITO                751 non-null    object
 31  PROVINCIA               751 non-null    object
 32  DEPARTAMENTO            751 non-null    object
 33  DNI_                    751 non-null    object
 34  CLIENTE                 751 non-null    object
 35  FECHA VENTA             751 non-null    datetime64[ns]
 36  HORA VENTA              751 non-null    datetime64[ns]
 37  DNI                     751 non-null    int64
 38  VENDEDOR                751 non-null    object
 39  CODIGO                  751 non-null    object
 40  PRECIO_WEB              751 non-null    float64
 41  N CUOTAS                751 non-null    int64
 42  ESTADO VENTA_WEB        751 non-null    object
 43  ORIGEN_SINCERADO        751 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(9), object(30)
memory usage: 264.0+ KB

In [186]:
df_cruce_webYcobranzas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 751 entries, 0 to 750
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   N°                      751 non-null    int64
 1   CÓDIGO DNI+LOTE         751 non-null    object
 2   ETAPA                   751 non-null    object
 3   LOTE                    751 non-null    object
 4   MES VTA                 751 non-null    object
 5   AÑO VTA                 751 non-null    int64
 6   ASESOR                  751 non-null    object
 7   VIGENTE                 751 non-null    object
 8   AREA_LOTES              751 non-null    float64
 9   TIPO DE LOTE            751 non-null    object
 10  FORMAPAGO               751 non-null    object
 11  PRECIO_COBRANZAS        751 non-null    float64
 12  CUOTAS CANCELADAS       751 non-null    int64
 13  CUOTAS VENC             751 non-null    int64
 14  CUOTAS PEND             751 non-null    int64
 15  TOTAL DE CUOTAS         751 non-null    int64
 16  MORA X DIA              751 non-null    object
 17  ESTADO VENTA_COBRANZAS  751 non-null    object
 18  STATUS LOTE             751 non-null    object
 19  STATUS PAGO             615 non-null    object
 20  CUOTAS VENC.1           751 non-null    int64
 21  STATUS MORA             183 non-null    object
 22  STATUS TOTAL            751 non-null    object
 23  STATUS TOTAL FINAL      751 non-null    object
 24  STATUS TOTAL FINAL 1    751 non-null    object
 25  STATUS TOTAL FINAL 2    751 non-null    object
 26  CORREO                  751 non-null    object
 27  TEL1                    751 non-null    object
 28  TEL2                    751 non-null    object
 29  DIR                     751 non-null    object
 30  DISTRITO                751 non-null    object
 31  PROVINCIA               751 non-null    object
 32  DEPARTAMENTO            751 non-null    object
 33  DNI_                    751 non-null    object
 34  CLIENTE                 751 non-null    object
 35  FECHA VENTA             751 non-null    datetime64[ns]
 36  HORA VENTA              751 non-null    datetime64[ns]
 37  DNI                     751 non-null    int64
 38  VENDEDOR                751 non-null    object
 39  CODIGO                  751 non-null    object
 40  PRECIO_WEB              751 non-null    float64
 41  N CUOTAS                751 non-null    int64
 42  ESTADO VENTA_WEB        751 non-null    object
 43  ORIGEN_SINCERADO        751 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(9), object(30)
memory usage: 264.0+ KB

### GUARDAR EXCEL PARA POWER BI MERGE DE CRM VENTAS LEADS Y COBRANZAS

In [139]:
#df_cruce_webYcobranzas.to_excel('Cruce_cobranzas.xlsx',index= False)

In [140]:
Ubicaciones = df_cruce_webYcobranzas[['CLIENTE','LOTE','TIPO DE LOTE','ESTADO VENTA_WEB','DISTRITO','PROVINCIA','DEPARTAMENTO']]

In [141]:
#Ubicaciones.to_excel('Ubicaciones_Tahiti.xlsx',index= False)