In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import glob
%matplotlib inline

In [2]:
proyeccion = pd.read_excel('Proyección Ventas 2023 Qarbón Trimestre(1).xlsx', sheet_name=None, header=2 ,parse_dates=['Fecha'],
                          dtype={'%': 'float'})

In [3]:
dfs = []
for sheet_name, df in proyeccion.items():
    df.drop(df.index[-2:], axis=0, inplace=True)
    dfs.append(df)

In [4]:
proyeccion2 = pd.concat(dfs, ignore_index=True)
proyeccion2

,Unnamed: 0,Fecha,Día,Venta Proyectada 1er y 2do Piso S/.,COCINA,BAR,Venta Proyectada Acumulada S/.,Venta Real Acum,Desviación % Acumulada,Venta Real 1er y 2do Piso S/.,COCINA.1,%,BAR.1,%.1
0,NaN,2023-01-01 00:00:00,Domingo,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00,0.0,0.00,0.000000
1,NaN,2023-01-02 00:00:00,Lunes,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00,0.0,0.00,0.000000
2,NaN,2023-01-03 00:00:00,Martes,7000.0,4200.0,2800.0,7000.0,9140.9,0.305843,9140.9,5484.54,0.6,3656.36,0.478274
3,NaN,2023-01-04 00:00:00,Miércoles,7000.0,4200.0,2800.0,14000.0,16785.8,0.198986,7644.9,4586.94,0.6,3057.96,0.400000
4,NaN,2023-01-05 00:00:00,Jueves,12000.0,7200.0,4800.0,26000.0,24149.1,-0.071188,7363.3,4417.98,0.6,2945.32,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,NaN,2023-03-27 00:00:00,Lunes,7000.0,4200.0,2800.0,276000.0,0.0,-1.000000,NaN,0.00,NaN,0.00,NaN
86,NaN,2023-03-28 00:00:00,Martes,7000.0,4200.0,2800.0,283000.0,0.0,-1.000000,NaN,0.00,NaN,0.00,NaN
87,NaN,2023-03-29 00:00:00,Miércoles,9000.0,5400.0,3600.0,292000.0,0.0,-1.000000,NaN,0.00,NaN,0.00,NaN
88,NaN,2023-03-30 00:00:00,Jueves,12000.0,7200.0,4800.0,304000.0,0.0,-1.000000,NaN,0.00,NaN,0.00,NaN
89,NaN,2023-03-31 00:00:00,Viernes,14000.0,8400.0,5600.0,318000.0,0.0,-1.000000,NaN,0.00,NaN,0.00,NaN

In [5]:
proyeccion2.drop(columns=['Unnamed: 0'], inplace= True)

In [6]:
proyeccion2.fillna(0, inplace=True)

In [7]:
proyeccion2['Desviación % Acumulada'] = proyeccion2['Desviación % Acumulada'].map('{:.2%}'.format)
proyeccion2['%'] = proyeccion2['%'].map('{:.2%}'.format)
proyeccion2['%.1'] = proyeccion2['%.1'].map('{:.2%}'.format)

In [8]:
proyeccion2

,Fecha,Día,Venta Proyectada 1er y 2do Piso S/.,COCINA,BAR,Venta Proyectada Acumulada S/.,Venta Real Acum,Desviación % Acumulada,Venta Real 1er y 2do Piso S/.,COCINA.1,%,BAR.1,%.1
0,2023-01-01 00:00:00,Domingo,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
1,2023-01-02 00:00:00,Lunes,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
2,2023-01-03 00:00:00,Martes,7000.0,4200.0,2800.0,7000.0,9140.9,30.58%,9140.9,5484.54,60.00%,3656.36,47.83%
3,2023-01-04 00:00:00,Miércoles,7000.0,4200.0,2800.0,14000.0,16785.8,19.90%,7644.9,4586.94,60.00%,3057.96,40.00%
4,2023-01-05 00:00:00,Jueves,12000.0,7200.0,4800.0,26000.0,24149.1,-7.12%,7363.3,4417.98,60.00%,2945.32,40.00%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-03-27 00:00:00,Lunes,7000.0,4200.0,2800.0,276000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
86,2023-03-28 00:00:00,Martes,7000.0,4200.0,2800.0,283000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
87,2023-03-29 00:00:00,Miércoles,9000.0,5400.0,3600.0,292000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
88,2023-03-30 00:00:00,Jueves,12000.0,7200.0,4800.0,304000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
89,2023-03-31 00:00:00,Viernes,14000.0,8400.0,5600.0,318000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%

In [9]:
#proyeccion2.to_excel('Proyecion Qarbon.xlsx', index= False)

In [34]:
def meses(nombre):
    df =  pd.read_excel('Proyección Ventas 2023 Qarbón Trimestre 2.xlsx', sheet_name=nombre, header=1 ,parse_dates=['Fecha'],
                          dtype={'%': 'float'})
    df.dropna(subset='Fecha',inplace = True)
    df.dropna(subset='Día',inplace = True)
    df['Var % Cocina'] = df['Var % Cocina'].map('{:.2%}'.format)
    df['Var % Bar'] = df['Var % Bar'].map('{:.2%}'.format)
    return df

In [35]:
abril = meses('Abril')
mayo = meses('Mayo')
junio = meses('Junio')

In [41]:
seg_trime = pd.concat([abril,mayo, junio])
seg_trime.shape

(91, 10)

In [46]:
seg_trime.rename(columns={'Venta Total Proyectada':'Venta Proyectada 1er y 2do Piso S/.',
                         'Venta Cocina Proyectada':'COCINA','Venta Bar Proyectada':'BAR',
                         'Venta Total Real':'Venta Proyectada Acumulada S/.','Venta Cocina Real':'Venta Real Acum',
                         'Var % Cocina':'%','Var % Bar':'%.1','Venta Bar Real':'Venta Real 1er y 2do Piso S/.'}, inplace = True)

In [58]:
seg_trime['Desviación % Acumulada'] = 0

In [59]:
seg_trime['Desviación % Acumulada'] = seg_trime['Desviación % Acumulada'].map('{:.2%}'.format)

In [43]:
proyeccion2

,Fecha,Día,Venta Proyectada 1er y 2do Piso S/.,COCINA,BAR,Venta Proyectada Acumulada S/.,Venta Real Acum,Desviación % Acumulada,Venta Real 1er y 2do Piso S/.,COCINA.1,%,BAR.1,%.1
0,2023-01-01 00:00:00,Domingo,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
1,2023-01-02 00:00:00,Lunes,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
2,2023-01-03 00:00:00,Martes,7000.0,4200.0,2800.0,7000.0,9140.9,30.58%,9140.9,5484.54,60.00%,3656.36,47.83%
3,2023-01-04 00:00:00,Miércoles,7000.0,4200.0,2800.0,14000.0,16785.8,19.90%,7644.9,4586.94,60.00%,3057.96,40.00%
4,2023-01-05 00:00:00,Jueves,12000.0,7200.0,4800.0,26000.0,24149.1,-7.12%,7363.3,4417.98,60.00%,2945.32,40.00%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-03-27 00:00:00,Lunes,7000.0,4200.0,2800.0,276000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
86,2023-03-28 00:00:00,Martes,7000.0,4200.0,2800.0,283000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
87,2023-03-29 00:00:00,Miércoles,9000.0,5400.0,3600.0,292000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
88,2023-03-30 00:00:00,Jueves,12000.0,7200.0,4800.0,304000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%
89,2023-03-31 00:00:00,Viernes,14000.0,8400.0,5600.0,318000.0,0.0,-100.00%,0.0,0.00,0.00%,0.00,0.00%

In [60]:
union = pd.concat([proyeccion2,seg_trime])

In [61]:
union.fillna(0,inplace=True)

In [62]:
union

,Fecha,Día,Venta Proyectada 1er y 2do Piso S/.,COCINA,BAR,Venta Proyectada Acumulada S/.,Venta Real Acum,Desviación % Acumulada,Venta Real 1er y 2do Piso S/.,COCINA.1,%,BAR.1,%.1
0,2023-01-01 00:00:00,Domingo,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
1,2023-01-02 00:00:00,Lunes,0.0,0.0,0.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
2,2023-01-03 00:00:00,Martes,7000.0,4200.0,2800.0,7000.0,9140.9,30.58%,9140.9,5484.54,60.00%,3656.36,47.83%
3,2023-01-04 00:00:00,Miércoles,7000.0,4200.0,2800.0,14000.0,16785.8,19.90%,7644.9,4586.94,60.00%,3057.96,40.00%
4,2023-01-05 00:00:00,Jueves,12000.0,7200.0,4800.0,26000.0,24149.1,-7.12%,7363.3,4417.98,60.00%,2945.32,40.00%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2023-06-26 00:00:00,Lunes,9000.0,4950.0,4050.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
27,2023-06-27 00:00:00,Martes,9000.0,4950.0,4050.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
28,2023-06-28 00:00:00,Miércoles,14000.0,7700.0,6300.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
29,2023-06-29 00:00:00,Jueves,12000.0,6600.0,5400.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%
30,2023-06-30 00:00:00,Viernes,15000.0,8250.0,6750.0,0.0,0.0,0.00%,0.0,0.00,0.00%,0.00,0.00%

In [63]:
#union.to_excel('Proyecion Qarbon.xlsx', index= False)